<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        Product::truncate();

        $spareparts = [
            '(NOT ACTIVE) BASIC BLACK INK 42ML WATERBASE',
            'AC AUTOMATIC VOLTAGE REGULATOR MODEL AVR 1000 (STA',
            'AC SERVO MOTOR 400W PANASONIC MHMD 042G1U',
            'ACCU GS',
            'ACTUATOR KIT 1/2 INCH UNTUK ROBO KIDZ 2000 A MERK',
            'ACTUATOR PNEUMATIC AIR CYLINDER SQ 50X25',
            'ADJUSTER KAKI CONVEYOR',
            'AIR ACCU',
            'AIR BIOTECH STAR - A',
            'AIR BIOTECH STAR - AN',
            'AIR COMPACT CYLINDER 32X25',
            'AIR COMPACT CYLINDER SDA 40x10',
            'AIR CYLINDER AIRTAC SAI (SI) 32 X 85 INCH',
            'AIR CYLINDER AIRTAC SAI (SI) 80 X 50 INCH',
            'AIR CYLINDER AIRTAC SC 32 x 50-S',
            'AIR CYLINDER AQ2B20-20D',
            'AIR CYLINDER CKD SCA2-00-100B-50',
            'AIR CYLINDER CM2B32-25Z',
            'AIR CYLINDER CQ2B50-25D2 2AI-86A MERK SMC',
            'AIR CYLINDER TYPE SD 32X16-RGJ MERK EMC',
            'AIR CYLINDER TYPE SQ50-25DZ 2A1-86A MAX 1,0 MPA ME',
            'AIR FILTER REGULATOR KOGANE R300-02',
            'AIR TAC FRL COMBINATION AFR 2000',
            'AIR TAC PNEUMATIC EQUIPMENT CYLINDER MODEL SC 32X5',
            'ALARM SENSOR MESIN DATE CODING',
            'AMPELAS HALUS CW 1000',
            'AMPLAS 500',
            'ANGEL SEAT VALVE ½ INCH - CF8M DN15 PN16',
            'ARANG KARBON BULAT',
            'ARM PRESSAN JG',
            'AS ARM JG',
            'AS GEAR PANJANG MESIN JG',
            'AS GEARBOX JELLY GUM',
            'AS KONEKTOR GEAR',
            'AS KUNINGAN "DIA. 1 3/4 IN X 95MM (160)',
            'AS KUNINGAN MESIN CUP TUNG TUNG',
            'AS MIXER LENGTH; 750MM, MAT: SS304, 2 BLADE (2 PAS',
            'AS PEN FILLING JELLVIT 01',
            'AUXILIARY LADN22 (ALAT BANTU KONTAKTOR) CONTACT BL',
            'BALING - BALING SHAFT MESIN JG',
            'BALL VALVE 1 1/2 INCH KUNINGAN',
            'BALL VALVE 1 1/2 INCH PVC',
            'BALL VALVE 1 1/2 INCH SS',
            'BALL VALVE 1 1/4 INCH KUNINGAN',
            'BALL VALVE 1 1/4 INCH SS',
            'BALL VALVE 1 INCH KUNINGAN',
            'BALL VALVE 1 INCH PVC',
            'BALL VALVE 1 INCH SS',
            'BALL VALVE 1/2 INCH GALVANIS MERK SANYO',
            'BALL VALVE 1/2 INCH KUNINGAN',
            'BALL VALVE 1/2 INCH SS',
            'BALL VALVE 1/4 INCH SS',
            'BALL VALVE 2 INCH KUNINGAN',
            'BALL VALVE 2 INCH PVC',
            'BALL VALVE 2 INCH SS',
            'BALL VALVE 3/4 INCH GALVANIS',
            'BALL VALVE 3/4 INCH KUNINGAN',
            'BALL VALVE 3/4 INCH SS',
            'BALL VALVE 3/8 INCH SS',
            'BALL VALVE 4 INCH PVC',
            'BALL VALVE 1 INCH SS FULLBORE',
            'BALL VALVE 1 1/2 INCH SS FULLBORE',
            'BALLAS PHILLIPS 18W',
            'BALLAST LAMPU PHILIPS 36W',
            'BALLAST TYPE BA ICE C MODEL S950',
            'BAN ARTCO MATI DIAMETER 34CM',
            'BAN DALAM 750.16',
            'BAN DALAM 900 GT',
            'BAN FORKLIFT MATI MERK ASENDO UK 5.00 - 8',
            'BAN FORKLIFT MATI MERK ASENDO UK 6.50-10',
            'BAN LUAR 1000',
            'BAN LUAR 750.16',
            'BASIC BLACK INK 42ML WATERBASE H-INK 11S+',
            'BATERAI A2 ALKALINE',
            'BATERAI A3 ALKALINE',
            'BATERAI ABC R20S',
            'BATERAI ALKALINE 6LR61 9 V',
            'BATERAI FOR FORKLIFT FE4P16E (450 AH)',
            'BATERAI OMRON CJ1W-BATO01',
            'BATERAI TADIRAN TL-5902',
            'BATERAI THERMO LR44',
            'BATRE CR 1220',
            'BATTERY CPU Tadiran 1/2 AA',
            'BATU GERINDA DUDUK 150x19x31 GREAT 130',
            'BATU GERINDA DUDUK 150x19x31 GREAT 80',
            'BATU GERINDA DUDUK 6x 3/4x1 1/4 Inch great 80',
            'BATU GERINDA DUDUK 6x3/4x1 1/4 Inch great 120',
            'BAUT JF 6 x 20 MM SS',
            'BAUT JF SS DIA: 1/4 x 3/4 INCH',
            'BAUT NYLON TATAKAN MOULD 15MMX30MM',
            'BEARING 207 51207 NSK',
            'BEARING 22213 EK/C3 MERK SKF',
            'BEARING 32209',
            'BEARING 51105',
            'BEARING 6000',
            'BEARING 6001',
            'BEARING 6001 2NSE',
            'BEARING 6002',
            'BEARING 6002 2RS SKF',
            'BEARING 6003',
            'BEARING 6003 2RS SKF',
            'BEARING 6004',
            'BEARING 6004 2RS SKF',
            'BEARING 6005',
            'BEARING 6005 2RS SKF',
            'BEARING 6005 ZZ',
            'BEARING 6006',
            'BEARING 6006 DU',
            'BEARING 6006 LU',
            'BEARING 6006 V',
            'BEARING 6006 ZZ',
            'BEARING 6007 2 RSR',
            'BEARING 6007 NTN ZZ',
            'BEARING 6008',
            'BEARING 6008 LLU',
            'BEARING 6009 ZZ',
            'BEARING 6014 DU',
            'BEARING 6014 NTN',
            'BEARING 607 Z FBJ',
            'BEARING 608 RS',
            'BEARING 608 ZZ',
            'BEARING 6200 2RS',
            'BEARING 6200 2RSR',
            'BEARING 6200-C-2HRS',
            'BEARING 6201 2RS SKF',
            'BEARING 6201 2NSE',
            'BEARING 6202',
            'BEARING 6202 2RS SKF',
            'BEARING 6203 2RS SKF',
            'BEARING 6203 ZZ',
            'BEARING 6204',
            'BEARING 6204 2RS SKF',
            'BEARING 6205 2RS SKF',
            'BEARING 6205 2RSR',
            'BEARING 6205 SKF',
            'BEARING 6206 2RS SKF',
            'Bearing 6206 ZZ FAG',
            'BEARING 6207',
            'BEARING 6207 LLB',
            'BEARING 6208 2RS SKF',
            'Bearing 6209 ZZ FAG',
            'BEARING 629 Z FBJ',
            'BEARING 6300',
            'BEARING 6301 2RS',
            'BEARING 6301 ZZ',
            'BEARING 6303',
            'BEARING 6303 2RS',
            'BEARING 6303 LLU',
            'BEARING 6304 2RS',
            'BEARING 6304 ZZ',
            'BEARING 6305',
            'BEARING 6305 2RS SKF',
            'BEARING 6305 ZZ',
            'BEARING 6307',
            'BEARING 6309 NSE',
            'BEARING 6310',
            'BEARING 6804 Z',
            'BEARING 6900ZZ',
            'BEARING 6901 ZZ NTN',
            'BEARING 6902',
            'BEARING 6902 LLU',
            'BEARING 6904',
            'BEARING 6907 2RS',
            'BEARING 696 SKF',
            'BEARING 696 Z ASB',
            'BEARING ARTCO',
            'BEARING CF 12 B',
            'BEARING FOR INDEXING GEARBOX JV01',
            'BEARING HF0812',
            'BEARING LFR 50 (LFR-50-8-6-2Z-HIJ)',
            'BEARING NACHI 30204J',
            'BEARING NTN 32022',
            'BEARING UC 203',
            'BEARING UC 204',
            'BEARING UC 204-12 FBJ',
            'BEARING UC 205',
            'BEARING UC 206',
            'BEARING UC 207- 20',
            'BEARING UC 208 - 24',
            'BEARING UC 211-32 (2 INCH )',
            'BEARING UC 210',
            'BEARING UCF 204',
            'BEARING UCF 207',
            'Bearing UCF 207-20',
            'BEARING UCFB 204 PILLOW BLOCK',
            'BEARING UCP 205 - 16 PILLOW BLOCK',
            'BEARING UCT 204',
            'BEARING UCT 205',
            'BELT CARTOON SEALER 1520 x 50',
            'BELT CARTOON SEALER 1548 x 50',
            'BELT RUBBER LINE 4 HIGH SPEED F SEQWT 5.150 X 90 E',
            'BELT RUBBER LINE 4 HIGH SPEED F SEQWT 6.350 X 90 E',
            'BIG M ANALOG PANEL METER 600/5 A',
            'BODY COLLET 2,4MM',
            'BOHLAM CUMI 12 V',
            'BOHLAM DESKBORARD',
            'BOHLAM HOLOGEN 24 V DC',
            'BOHLAM INDIKATOR',
            'BOHLAM K.1 KECIL',
            'BOHLAM K.1 BESAR',
            'BOHLAM K.2 BESAR',
            'BOHLAM K.2 KECIL',
            'BOHLAM KABUT/BOHLAM BEMPER',
            'BOHLAM LED KECIL 20 WATT',
            'BOHLAM LED KECIL 40 WATT',
            'BOHLAM LED PHILIP 40 WATT',
            'BOHLAM PHILLIPS 45 WATT',
            'BRACKET HEATER BESAR FL',
            'BRACKET OUTPUT PRODUCT',
            'BRAKET OUTPUT (POMPA SEDOT JELY GUM)',
            'BRAKET POMPA INLET OUTLET',
            'BUSHING AS CENTER',
            'BUSHING AS CENTER BAJA-JG',
            'BUSHING KIT',
            'BUSHING MEKANIK MESIN ES SALJU',
            'BUSHING MEKANIK PISAU',
            'BUSI FORKLIFT',
            'CAP CARBURATOR',
            'CARBON BRUSH 4 X 4',
            'CARBON BRUSH BULAT (BENTUNG TABUNG)',
            'BUTTERFLY VALVE SS SANITARY 2 INCH',
            'CARBON BRUSH CB - 203 A',
            'CARBON BRUSH CB - 459',
            'CARBON BRUSH CB - 64',
            'CARBON BRUSH CB 85A',
            'CARBON BRUSH MH04',
            'CASTABLE CEMENT C-18',
            'CASTROL TRIBOL GR HT 2',
            'CAT ANTI PANAS 400 DERAJAT WARNA SILVER',
            'CAT BATU CANDI MERK PROPAN STONE CARE WARNA BLACK',
            'CAT BESI MERK AVIAN SUPER WHITE',
            'CAT BESI MERK NIPPON PAINT NP 610 BRIGHT BLUE',
            'CAT BESI MERK NIPPON PAINT NP 622 GREY',
            'CAT BESI MERK NIPPON PAINT NP 631 WARNA COCO BROWN',
            'CAT BESI MERK NIPPONT PAINT BS9102 SUPER WHITE',
            'CAT BESI MERK YOKO BLUE WARNA 779 SUNFLOWER',
            'CAT BESI MERK YOKO BLUE WARNA SUPER BLACK',
            'CAT BESI NIPPON PAINT NP 649 WARNA BLUE BELL',
            'CAT BESI NIPPON PAINT NP 680 SHINE',
            'CAT BESI WARNA COKLAT NP 663',
            'CAT GENTENG MERK NIPPON PAINT WARNA PUTIH',
            'CAT LAPANGAN MERK PROPAN WARNA ORANGE',
            'CAT MERK PROPAN GEMINI WARNA KUNING 0,9L',
            'CAT PILOK BESI MERK SUZUKA SC-135 WARNA METALICA S',
            'CAT TEMBOK AQUAPROOF ABU ABU 061',
            'CAT TEMBOK MERK AVITEX WARNA PUTIH',
            'CATRIDGE 40 INCH 1 MICRON',
            'CATRIDGE AA',
            'CATRIDGE AA (WATERBASE, S/N 180308169, INK TYPE 26S)',
            'CATRIDGE HEATER + NEPEL 500W 220V, UK 16,1x155MM,',
            'CATRIDGE HEATER HTI 16,64X922 MM, 2000W-220V, TERM',
            'CATRIDGE HEATER HTI 19,8X350 MM, 2500W-220V, TERMI',
            'CATRIDGE HEATER TANAM DALAM DIA 20X350 MM, 2500W-2',
            'CATRIDGE SOLVENTBASE T.JET',
            'CETEKAN ON DAN OF',
            'CHNT CONTROL DEVICE ELEKTROMAGNETIK JD1A-90 AC 22',
            'CHUCK MATA BOR DRILL BASS 3.2 MM',
            'CINCIN KARBON MH04',
            'CLEANER LI JUN',
            'CLEANER PRINTFLEX',
            'Cleaning Solution V901-Q',
            'CLEANING SOLVENT',
            'COLLET 2,4MM',
            'CONTACT CLEANER',
            'CORONG JELY GUM',
            'CORONG JELY STICK YOGU UK 52',
            'CORONG STICK',
            'COUPLING ELEMENT',
            'CURRENT TRANSFORMERS MSQ-30 SERIES 100/5 A FORT',
            'CURRENT TRANSFORMERS MSQ-60 SERIES 600/5 A FORT',
            'CUTTING MESIN C6 PISAU PUNCH FULL AUTO DIA 44MMX10',
            'CUTTING/PISAU PLANNER MAKITA',
            'CUTTING/PISAU ZIGZAG 135 MM TJM',
            'CUTTING/PISAU ZIGZAG UK 175 MM JELGUM KJT',
            'CUTTING/PISAU ZIGZAG UK 175 MM JELGUM TJM',
            'CYLINDER PUMP KJT',
            'DANA PAINT HARDENER LEM 0,3 LITER',
            'DIAPRAGM VALVE 1 1/4 INCH SS',
            'DIGITAL OUTPUT MODULE COMPONENT PLC',
            'DIGITAL PRESSURE DP-102 MERK PANASONIC',
            'DOP 2 INCH PVC',
            'DOUBLE NAPLE 1/2 INCH SS',
            'DOUBLE NAPPLE 1 1/2 INCH SS',
            'DOUBLE NAPPLE 1 1/4 INCH SS',
            'DOUBLE NAPPLE 1 INCH SS',
            'DOUBLE NAPPLE 1/2 INCH GALVANIS',
            'DOUBLE NAPPLE 1/4 INCH SS',
            'DOUBLE NAPPLE 2 1/2 INCH GALVANIS',
            'DOUBLE NAPPLE 2 INCH SS 201',
            'DOUBLE NAPPLE 3/4 INCH SS',
            'DRIVING SHAFT',
            'DRIVING WHEEL',
            'DUDUKAN FILTER SOLAR ATAS PS.120',
            'DUDUKAN HEATER STICK DIA: 16MM',
            'DUDUKAN LAMPU NEON KECIL (BARU)',
            'DUDUKAN PER STICK UK, P: 1,6 cm',
            'DUDUKAN RELAY 8 PIN MERK EWIG 36 X 80 MM D9F 14 A',
            'DUDUKAN RELAY 8 PIN PS-08 2-M4X20MM',
            'DUDUKAN RELAY DTF14A 36X68MM MERK EWIG',
            'DUDUKAN RELAY PTF14A 36X68MM',
            'DUDUKAN SENSOR FIBER OPTIK',
            'ELBOW 1 1/2 INCH GALVANIS',
            'ELBOW 1 1/2 INCH SS',
            'ELBOW 1 1/4 INCH GALVANIS',
            'ELBOW 1 INCH GALVANIS',
            'ELBOW 1 INCH PVC',
            'ELBOW 1 INCH SS',
            'ELBOW 1/2 INCH GALVANIS',
            'ELBOW 1/2 INCH PVC',
            'ELBOW 2 1/2 INCH PVC',
            'ELBOW 2 INCH GALVANIS',
            'ELBOW 2 INCH PVC',
            'ELBOW 2 INCH SS',
            'ELBOW 3 INCH PVC',
            'ELBOW 3 INCH SS',
            'ELBOW 3/4 INCH PVC',
            'ELBOW 3/4 INCH SS',
            'Elbow 3/8 inch SS',
            'ELBOW 4 INCH PVC',
            'ELBOW 4 INCH SS',
            'ELBOW 6 INCH PVC',
            'ELBOW BAJA SEAMLESS 1 1/2 INCH PIPA HITAM',
            'ELBOW SANITARY 2 INCH (50MM)',
            'ELBOW SANITARY 25MM (1 INCH)',
            'ELBOW SANITARY 316L 1 1/2 INCH',
            'ELBOW SANITARY 38MM ( 1,5 INCH)',
            'ELBOW SEAMLESS 2 INCH (PIPA HITAM)',
            'ELCO 1000UF 10V',
            'ELCO 33UF 450V',
            'ELCO 470UF 25V',
            'ELCO 470UF 35V',
            'ELECTRODE HOLDER PS-3S',
            'ELEKTRODA TIP PT31',
            'ELEMENT 150 W 230V ( 88MM X 7MM )',
            'ELEMENT 230V 300W UK. 9.5 X 70',
            'ELEMENT 300 WATT 220 V',
            'ELEMENT 400W 220V (80MMX10MM)',
            'ELEMENT 400W 220V UK. 80MM X 405MM',
            'ELEMENT 500W 220V (160MMX12MM)',
            'ELEMENT PRESS PACKING',
            'ELEMENT PRESS PLASTIK',
            'ELEMENT ST11209 220V 150W UK. 8CM X 6MM',
            'HEATER CATRIDGE 125W 230V, DIA: 10 MM X 40 MM',
            'HEATER STRIP 300W 230V, 250MM X 22MM',
            'EXHAUST FAN',
            'FAN AC AXIAL BLOWER 120 X 120 X 38MM 220 VAC',
            'FAN EWIG MODEL 150X150X50 BALL BEARING 220-240 V, 50/60 HZ, 0,29 A 35 W (KIPAS)',
            'FAN NMB MODEL 4715 KL-05W-B40 (KIPAS)',
            'FAN NMB-MAT MINEBEA 4710KL-05W-B4912025 12CM 24VDC',
            'FERRULE 2 INCH SANITARY',
            'FERRULE 1 INCH SANITARY',
            'FERULLE 2 INCH',
            'FERULLE SANITARY 316L 1 1/2INCH',
            'FIBER SENSOR BF3RX MERK AUTONICS 12-24V DC',
            'FIBER SENSOR BF4R MERK AUTONICS 12-24V DC',
            'FILTER AQUARIUM 2x1',
            'FILTER OLI C - 1104',
            'FILTER OLI C 1115 F1',
            'FILTER OLI C 1539 F3',
            'FILTER OLI C-1004',
            'FILTER OLI C-1012',
            'FILTER OLI C-1142',
            'FILTER SOLAR ATAS FC-1003',
            'FILTER SOLAR BAWAH F-1002',
            'FILTER SOLAR BAWAH SF-1004',
            'FILTER UDARA F1 (A 1014)',
            'FILTER UDARA F3 ( D821575)',
            'FITTING APC 10-04',
            'FITTING APC 10-02',
            'FITTING APC 10-03',
            'FITTING APC 12-01',
            'FITTING APC 12-02',
            'FITTING APC 12-03',
            'FITTING APC 12-04',
            'FITTING APC 16-04',
            'FITTING APC 16-03',
            'FITTING APC 6-01',
            'FITTING APC 6-02',
            'FITTING APC 6-03',
            'FITTING APC 6-04',
            'FITTING APC 6-M5',
            'FITTING APC 8-01',
            'FITTING APC 8-02',
            'FITTING APC 8-03',
            'FITTING APC 8-04',
            'FITTING APE 10',
            'FITTING APE 12',
            'FITTING APE 16',
            'FITTING APE 6',
            'FITTING APE 8',
            'FITTING APE 8-01',
            'FITTING APL 04-01',
            'FITTING APL 10-01',
            'FITTING APL 10-02',
            'FITTING APL 10-03',
            'FITTING APL 10-04',
            'FITTING APL 12',
            'FITTING APL 12-01',
            'FITTING APL 12-02',
            'FITTING APL 12-03',
            'FITTING APL 12-04',
            'FITTING APL 16-03',
            'FITTING APL 16-04',
            'FITTING APL 6-01',
            'FITTING APL 6-02',
            'FITTING APL 6-03',
            'FITTING APL 6-04',
            'FITTING APL 6-M5',
            'FITTING APL 8-01',
            'FITTING APL 8-02',
            'FITTING APL 8-03',
            'FITTING APL 8-04',
            'FITTING ASC 10-01',
            'FITTING ASC 10-02',
            'FITTING ASC 10-03',
            'FITTING ASC 10-04',
            'FITTING ASC 12-01',
            'FITTING ASC 12-02',
            'FITTING ASC 12-03',
            'FITTING ASC 12-04',
            'FITTING ASC 16-03',
            'FITTING ASC 16-04',
            'FITTING ASC 6-01',
            'FITTING ASC 6-02',
            'FITTING ASC 6-03',
            'FITTING ASC 6-04',
            'FITTING ASC 6-M5',
            'FITTING ASC 8-01',
            'FITTING ASC 8-02',
            'FITTING ASC 8-03',
            'FITTING ASC 8-04',
            'FITTING BOHLAM GANTUNG',
            'FITTING LAMPU GANTUNG WD (KERAMIK)',
            'Fitting lampu plafond segi empat',
            'FITTING LAMPU TL VEER',
            'FITTING PNEUMATIC Y 8MM',
            'FITTING REDUCER 12-10',
            'FITTING REDUCER 12-16',
            'FITTING REDUCER 8-10',
            'FITTING REDUCER 8-6',
            'FITTING SOCK 10',
            'FITTING SOCK 12',
            'FITTING SOCK 16',
            'FITTING SOCK 6',
            'FITTING SOCK 8',
            'FITTING Y 6-4',
            'FLANG SEAL VERTICAL',
            'FLANGE 1 INCH SS',
            'FLANGE 2 INCH SS',
            'FLANGE 4 INCH SS',
            'FLANGE SEAL HORIZONTAL PER TEKAN BELAKANG',
            'FLASER',
            'FLASH BAND 2 INCH',
            'FLIGHT MODULAR F07',
            'FLOATLESS OMRON TYPE 61F-G-AP 2 RELAY',
            'FLOATLESS RELAY LEVEL SW TYPE AFR-1 220V AC 50/60',
            'FUEL FILTER GENSET',
            'FUSE 10A KECIL',
            'FUSE 10 A',
            'FUSE 15 A',
            'FUSE 2 A',
            'FUSE 3 A',
            'FUSE 6A KECIL',
            'FUSE HOLDER 3 KERAMIK',
            'FUSE HOLDER HY-F15-IA 250V AC',
            'FUSE HOLDER KERAMIK 2A',
            'FUSE KERAMIK 10 A 220V',
            'FUSE KERAMIK 25 AMP',
            'FUSE KERAMIK 2A',
            'FUSE KERAMIK R015 RT14 5 A',
            'FUSE LINDER NT2 355A',
            'FUSE LINK NT-2 (316-660V)',
            'GATE VALVE 2 Inchi KUNINGAN',
            'GEAR / SPROKET TEFLON 25 MATA DIAMETER AS 24MM RS5',
            'GEAR NANAS',
            'GEAR PRESSAN HORIZONTAL',
            'GEARBOX TYPE 60 RATIO 1:30 MERK CENTA',
            'GLOBE VALVE STEAM DN 50 (2 INCH)',
            'GREEN ORING FULL DATE CODING HP-241',
            'GREEN ORING FULL SET HP-241',
            'GUIDE BELT FRB 770',
            'GUIDE BELT FRB 980',
            'HALBASIT BELT 1030x200',
            'HALBASIT BELT 1380X250',
            'HALBASIT BELT 1658 x 250',
            'HALBASIT BELT UK 2238 x 250 (PAKAI SLIDING)',
            'HEATER 1500w 220v, Dia: 19mm x 350mm, KABEL: 25cm',
            'HEATER 150W 220V, 51,04MM X 10,22MM',
            'HEATER CATRIDGE 150W 220V, Ø9,82 MM X 83,03 MM, KABEL FLEXIBLE 2 METER',
            'HEATER 175W 110V, 110 MM X 24 MM',
            'HEATER 175W 110V, 150 MM X 24 MM',
            'HEATER 175W 220V, 150 MM X 24 MM',
            'HEATER 2000W 220V, 16.64X922 MM, KABEL FLEXIBEL 25',
            'HEATER CATRIDGE 2000W 220V, 15 MM x 735 MM, KABEL FLEXIBLE 25 CM',
            'HEATER 2000W 220V, dia: 16,64MM x x922MM',
            'HEATER 220 V 175W Uk. 150x24mm',
            'HEATER 220 V, 300 W, PANJANG;205 MM DIAMETER 10 MM',
            'HEATER 2500W 220V, DIA;19MM X 350MM, KABEL;25CM',
            'HEATER 250W 220V, 240MM X 8MM',
            'HEATER 300W 220V, 101,12MM X 9,73MM',
            'HEATER CATRIDGE 300W 220V, 205 MM X 10 MM',
            'HEATER 300W 230V, 90MM X10MM',
            'HEATER 300W, 220 V, PANJANG;91.35 MM DIAMETER 12.0',
            'HEATER 300W 220V, 89,1 MM X 16,1 MM',
            'HEATER 400 W, 220 V, PANJANG 160MM X DIAMETER 15,6',
            'HEATER 400W 220V, 42CM X 7,90MM',
            'HEATER 40W 110V, 30MM X 10MM',
            'HEATER 500 W, 220 V, PANJANG; 150 MM, DIAMETER 12',
            'HEATER 500 W, 220 V, PANJANG;80MM, DIAMETER ; 12MM',
            'HEATER 500 W, 230 V, PANJANG 16 CM, 14,61 MM',
            'HEATER 600 W, 220 V, P:230 MM DIAMETER 17,1MM (MS',
            'HEATER CATRIDGE 80W 220V, Ø12,04 MM X 36,1 MM, KABEL FLEXIBLE 25 CM',
            'HEATER BULAT (UNTUK MESIN HORIZONTAL 300 W 230 V)',
            'HEATER CATRIDGE 500 W, 220 V, PANJANG;160MM X DIAM',
            'HEATER ELEMENT GELANG (250 W 220 V)',
            'HEATER TUBULAR STRAIGHT 1500W 220V, Ø8 MM X 135 CM (MC.FL)',
            'HEATER STRIP 300W 230V, 250 MM X 22 MM',
            'Heater tabung 300w 220v, panjang:245mm dia:10mm',
            'HEATER TUBULAR STRAIGHT DIA: 11mm x 18,5mm x 350mm, 220v 10',
            'HEATING BLOK HP-241',
            'TEMPERATURE HEATING CONTROLLER EMKO ESM 3710',
            'HIGH TEMPERATURE PAINT MAX TEMP 300 DEG CELCIUS',
            'HOT INK ROLL',
            'TINTA INK IC-2BK124',
            'INK JET PRINTER MEREK ELFIN1S',
            'INVERTER DELTA VFD007L21A 0,75KW, 230V 1 PHASE',
            'INVERTER FUJI ELEKTRIK FRENIC MINI FRN0006 C25-7A',
            'INVERTER MINI S 2S0007 M (EASY DRIVE)',
            'INVERTER TYPE SV008iG5A-2, INPUT 200-230V 1Hp',
            'ISOLASI LISTRIK',
            'ISOLASI TAHAN PANAS INCH 25 MM (Nitto Denko)',
            'JARUM LAS ARGON 2,4MM',
            'JARUM LAS ARGON 2.4MM',
            'JOIN COUPLE',
            'KABEL HEAD',
            'KABEL HEATER',
            'KABEL INJEKTOR',
            'Kabel NYY 2x1,5mm (kawat)',
            'KABEL PARALEL ACCU',
            'KABEL PRINT HEAD',
            'KABEL THERMO COUPLE 2 METER TYPE FT-K/J-M6',
            'KABEL THERMO COUPLE 3 M TYPE FT-K/J-M6',
            'KAIN MAJUN',
            'KANVAS REM ( BRAKE SHOE)',
            'KANVAS REM RCA MB 162517',
            'KAPASITOR 1,5 MIKRO',
            'KAPASITOR 250 MFD',
            'KAPASITOR 300MFD 125 VAC',
            'KAPASITOR 400/450VAC 18 MIKRON F',
            'KAPASITOR CBB6-5 16uF +-5% 500V AC 50/60Hz',
            'KAPASITOR CBB60',
            'KARABINER SEGITIGA',
            'KARAKTER 3 X 3,0 X 6,8 ANGKA EXPIRE DELAPAN (8) HRZ',
            'KARAKTER 3 X 3,0 X 6,8 ANGKA EXPIRE DUA (2) HRZ',
            'KARAKTER 3 X 3,0 X 6,8 ANGKA EXPIRE EMPAT (4) HRZ',
            'KARAKTER 3 X 3,0 X 6,8 ANGKA EXPIRE ENAM (6) HRZ',
            'KARAKTER ANGKA EXPIRE GARING (/) HRZ',
            'KARAKTER 3 X 3,0 X 6,8 ANGKA EXPIRE LIMA (5) HRZ',
            'KARAKTER 3 X 3,0 X 6,8 ANGKA EXPIRE NOL (0) HRZ',
            'KARAKTER 3 X 3,0 X 6,8 ANGKA EXPIRE SATU (1) HRZ',
            'KARAKTER 3 X 3,0 X 6,8 ANGKA EXPIRE SEMBILAN (9) HRZ',
            'KARAKTER 3 X 3,0 X 6,8 ANGKA EXPIRE TIGA (3) HRZ',
            'KARAKTER 3 X 3,0 X 6,8 ANGKA EXPIRE TUJUH (7) HRZ',
            'KARAKTER HP241 2LINE 2 X 4 X 14,5 ANGKA 2',
            'KARAKTER HP241 2LINE 2 X 4 X 14,5 ANGKA 4',
            'KARAKTER HP241 2LINE 2 X 4 X 14,5 ANGKA 7',
            'KARAKTER HP241 2LINE 2 X 4 X 14,5 ANGKA 0',
            'KARAKTER HP241 2LINE 2 X 4 X 14,5 ANGKA 1',
            'KARAKTER HP241 2LINE 2 X 4 X 14,5 ANGKA 5',
            'KARAKTER HP241 2LINE 2 X 4 X 14,5 ANGKA 6',
            'KARAKTER HP241 2LINE 2 X 4 X 14,5 ANGKA 8',
            'KARAKTER HP241 2LINE 2 X 4 X 14,5 ANGKA 3',
            'KARAKTER HP241 2LINE 2 X 4 X 14,5 ANGKA 9',
            'KARAKTER GARIS MIRING ( / )',
            'KARAKTER 2 X 4 X 14,5 HURUF A',
            'KARAKTER 2 X 4 X 14,5 HURUF B',
            'KARAKTER 2 X 4 X 14,5 HURUF C',
            'KARAKTER 2 X 4 X 14,5 HURUF D',
            'KARAKTER 3 X 3,0 X 6,8 HURUF E (HRZ)',
            'KARAKTER 3 X 3,0 X 6,8 HURUF F (HRZ)',
            'KARAKTER 3 X 3,0 X 6,8 HURUF G (HRZ)',
            'KARAKTER 2 X 4 X 14,5 HURUF H',
            'KARAKTER 2 X 4 X 14,5 HURUF I',
            'KARAKTER 2 X 4 X 14,5 HURUF J',
            'KARAKTER 2 X 4 X 14,5 HURUF K',
            'KARAKTER 2 X 4 X 14,5 HURUF L',
            'KARAKTER 2 X 4 X 14,5 HURUF M',
            'KARAKTER 2 X 4 X 14,5 HURUF N',
            'KARAKTER 3 X 3,0 X 6,8 HURUF P (HRZ)',
            'KARAKTER 2 X 4 X 14,5 HURUF S',
            'KARAKTER 3 X 3,0 X 6,8 HURUF X (HRZ)',
            'KARAKTER TITIK ( . )',
            'KARET SILICONE PENAHAN KARAKTER',
            'KAWAT LAS SS 2,6 MM (NIKO NSN 308)',
            'KAWAT LAS LB 52, 2,6 MM X 350 MERK KOBE STEEL WELDI',
            'KAWAT LAS RB 26, 2,6 MM X 350 MERK KOBE STEEL WELDI',
            'KAWAT NIKLIN 4 MM X 0,4 MM SS',
            'KAWAT SELING 0,5 MM',
            'KAWAT TALI BETON',
            'KAWAT TALI LUNAK 0,5 MM SS',
            'KAWAT TALI LUNAK 1,5 MM SS',
            'KAWAT TALI LUNAK 2 MM SS',
            'KENOP NOZLE JELLY GUM PANJANG TJM',
            'KENOP NOZLE JELLY GUM PENDEK TJM',
            'KENOP NOZLE PANJANG KJT',
            'KENOP NOZLE PENDEK KJT',
            'KERAMIK/ SWIRL RING CUT 49 SHORT',
            'KLAKSON',
            'KLEM KAWAT UK 1 1/2 INCH',
            'KLEM SELANG 1 INCH',
            'KLEM SELANG 2 INCH',
            'KLEM SELANG 3/8 INCH',
            'KLEM SELANG 1 1/2 inch',
            'KLEM SELANG 1/2 inch',
            'KLEM SELANG 3/4 inch',
            'KLEMAN ACCU',
            'KNOP JELVIT',
            'KONTAKTOR LC1D09M7 SCHNEIDER',
            'KONTAKTOR LC1D12M7 SCHNEIDER AC1: 25A',
            'KONTRAKTOR LC1D32M7 50A SCHNEIDER',
            'KONTRAKTOR LC1D32Q7 32A 380V 3P SCHNEIDER',
            'KONTRAKTOR LC1D40Q7 40A 380V 3P SCHNEIDER',
            'KRAN AIR 1/2 INCH',
            'KRAN AIR 3/4 INCH',
            'BALL VALVE 3/4 INCH SS FULL BORE',
            'KRAN COMPRESSOR ANGIN 1/4 INCH CHROME',
            'KRAN VALVE 1 1/4 INCH KUNINGAN',
            'KRANZ 1/2 INCH GALVANIS',
            'KUAS 2 INCH',
            'LAKBAN ANTI PANAS NITTO DENKO 50 MM',
            'LAKBAN KERTAS MERK DAIMARU',
            'LAKBAN KERTAS MERK JOYKO',
            'LAMPU DOWNLIGHT 24 WATT 150 MM',
            'LAMPU DOWNLIGHT LED 24 WATT 300 MM',
            'Lampu led 18 watt philips + cover (isi 2)',
            'LAMPU LED 19 WAT',
            'LAMPU NEON 36W PHILLIPS + MIKA BOX SET',
            'LAMPU TL 18 WATT LED PHILLIPS',
            'LAMPU TL 18 WATT PHILLIPS',
            'LAMPU NEON PHILIPS 36W',
            'Lampu sorot LED Hokistar 50w',
            'LAMPU TEMBAK / SOROT 150 WATT LED',
            'LAMPU TEMBAK LED 200W',
            'LAMPU TL 36 W LED + BOX',
            'LAMPU TL 36 WATT PHILLIPS LED',
            'LAMPU TL 18 WATT PHILLIPS',
            'LAMPU TL 18 WATT PHILIPS LED',
            'LAMPU TL 36 WATT PHILLIPS',
            'Lampu Highbay 100 Watt LED / Lampu UFO',
            'LAMPU ULTRA VIOLET (UV) MERK VIQUA S950RL HO',
            'LAMPU UV AQUARIUM 9 WATT',
            'LAMPU VESTA LED 50W',
            'LANGSOL',
            'LEM AIBON',
            'LEM BESI DEXTONE',
            'LEM DEXTONE SILICONE SEALENT',
            'LEM KOREA / DEXTONE',
            'LEM PIPA',
            'LIMIT SWITCH 16A 250V AC RV-166-1C25',
            'LIMIT SWITCH CMV104D 250V AC',
            'LIMIT SWITCH KECIL & RODA',
            'LIMIT SWITCH Z - 15GW-B',
            'LIMIT SWITCH Z - 15GW2-B',
            'LIMIT SWITCH Z - 15HW78-B',
            'LONG BACK UP',
            'MAGNETIC SWITCH (KONTAKTOR) EWIG',
            'MAGNETIC SWITCH C10 3,6A 400V',
            'MAGNETIC SWITCH EWIG MODEL MS-N10 COIL 380 (1,7-2,5 A)',
            'MAGNETIC SWITCH INSCOM 6-10 A',
            'MAGNETIC SWITCH INSCOM MS-K10 380 V HEATER 5A (4-6)',
            'MAKE UP INK TH 18',
            'MAKE UP MC-2BK124',
            'MAKE UP PW-700',
            'Make Up V706-D',
            'MATA BOR 18 MM - MERK ALDO',
            'MATA BOR 19MM',
            'MATA BOR 2MM',
            'MATA BOR NACHI 3.5',
            'MATA BOR NACHI 4',
            'MATA GERGAJI BESI MERK SANDFLEX 12 INCH/300MM',
            'MATA GERINDA DISK POLI CLEAN 4 INCH',
            'MATA GERINDA KAIN JEANS 4 INCH',
            'MATA GERINDA POLES AMPLAS GRIT A 120 4 INCH / FLAP DISK',
            'MATA GERINDA POLES MERAH ATAU PENGHALUS 4 INCH',
            'MATA GERINDA POTONG 4 Inchi WD',
            'MATA GERINDA POTONG NIPON RESIBON 14" 335x3x25,4MM',
            'MATA GERINDA POTONG TIPIS SS MERK WD 4 INCH',
            'MCB 1 PHASE 16A',
            'MCB 1 PHASE 20 AMP',
            'MCB 1 PHASE 25A-SCHNEIDER',
            'MCB 3 PHASE 16 A',
            'MCB 3 PHASE 32A',
            'MCB C16 DOMF01116 230 V MEREK SCNEIDER',
            'MCB C16 NXB-63 3P',
            'MCB C32 DOMF01132 230 V MEREK SCHNEIDER',
            'MCCB 3 PHASE 50A',
            'MECHANICAL SEAL 15 X 38.5 (BESAR)',
            'MECHANICAL SEAL CEA AS 14 MM - Lowara',
            'MECHANICAL SEAL KECIL',
            'MECHANICAL SEAL MERK POMPA CNP SEAL CDLF 32-85 MEC',
            'MECHANICAL SEAL TYPE MS-12 / DB125',
            'MECHANICAL SEAL UHT',
            'MICRO SWITCH CHINT YBLXW-6/11BZ',
            'MIKA BOX LED',
            'MIKA KODOK',
            'MIKI PULLEY ELEKTRO MOTOR',
            'MIKI PULLEY GEAR BOX',
            'MINYAK REM',
            'MORTISE DOOR LOCK',
            'MOTOR 220V 25W 1300RPM PEEI MOGER M-4IK25N-C',
            'MOTOR CIRCUIT BREAKER EZC100B3050',
            'MOTOR CIRCUIT BREAKER EZC100F3080',
            'MOTOR MIXER A/C GEAR MOTOR POWER 1HP MERK LI MING,',
            'MOTOR ROLLER FILM',
            'MUR DUDUKAN PER STICK',
            'NH-TYPE FUSE BASE (NH3 630 A) 690 V AC',
            'NH-TYPE FUSE LINK (NH2 355 A 500 V AC) EWIG',
            'NH-TYPE FUSE LINK (NH3 500 A 500 V) EWIG',
            'NOZLE POMPA JELLY GUM',
            'NOZLE ROBOKIDS',
            'NOZLE TIP PLASMA PT31',
            'NYLON GUIDE RAIL 12CJD',
            'NYLON VALVE (FL13)',
            'OIL SEAL 16 -30-7',
            'OIL SEAL RST 45-72-8',
            'OIL SEAL TC 12-21-7',
            'OIL SEAL TC 12-24-7',
            'OIL SEAL TC 12-28-7 NOK',
            'OIL SEAL TC 17-28-6',
            'OIL SEAL TC 20-35-7',
            'OIL SEAL TC 20-36-7',
            'OIL SEAL TC 25-40-7',
            'OIL SEAL TC 30-50-10',
            'OIL SEAL TC 45-65-10',
            'OIL SEAL TC 50-80-10',
            'OLI GARDAN',
            'OLI HYDROLIK FORKLIFT SAE 10',
            'OLI MESIN SAE 40 PERTAMINA SV',
            'OLI POWER STERING',
            'ORING / SEAL 140 TYPE (SET)',
            'ORING BIRU',
            'ORING WHITE SILICONE 2 X 7 MM (HKF)',
            'ORING WHITE SILICONE 21 X 3 MM (NFB)',
            'ORING WHITE SILICONE 2,6 X 20,5 MM (FA)',
            'ORING HIJAU',
            'ORING PUTIH',
            'ORING RED SILICONE 57X62X2,5',
            'ORING SILICONE  WHITE 2 X 30,5 MM',
            'ORING SILICONE ID: 30MM X 4.5MM',
            'ORING UK 2,6 X 20,5MM',
            'ORING VITON ID 30MM, OD 37MM, CS 3,5MM',
            'ORING VITON UK 3,5 X 28,5 MM',
            'ORING VITON UK 3MM X 25MM X 31MM',
            'ORING VITON UK 9 X 6 X 2MM',
            'ORING WHITE SILICONE ID: 21MM, OD: 26MM, CS: 2,5MM',
            'ORING WHITE SILICONE ID: 59MM, OD: 64,5MM, CS: 2,4',
            'ORING WHITE SILICOONE ID: 14MM, OD: 20MM, CS: 2,5M',
            'OUTPUT PRODUCT MESIN JG',
            'OVER LOAD GV3M80/ 56-80A',
            'OVER LOAD RELAY 1 - 1.6 AMP LRD06',
            'PACKING AS RODA',
            'PACKING ASBES PITA',
            'PANEL METER 500V SF-96 FORT',
            'PANEL VOLTMETER FORT 200 AMP MODEL SF-96',
            'PEEI MOGER M-2DK6N-F18 6W 24VDC, 1800 RPM DM-4522',
            'PEGAS VIBRATING',
            'PELAMPUNG CATRIDGE',
            'PER DUDUKAN BUSHING MESIN STICK',
            'PER MESIN DATE CODING (JG)',
            'PER PISAU JG, PL-36,04; DD-5,03; DK-1; DL-9; L-37',
            'PER PRESSAN UK. 20MM X 90MM WRN KUNING AM',
            'PER SS DIAMETER DALAM 14MM, PANJANG 50MM, TINGGI 0',
            'PER STAINLES DIA DALAM 9MM PANJANG 50MM',
            'PER TARIK DATE CODING HP-241 (JG)',
            'PER TARIK ENCORDER DOMINO',
            'PER TARIK EXPIRE P: 29MM, DL: 5,6MM',
            'PER TARIK HORIZONTAL, PL-138,36; DK-2,81; DL-22,01',
            'PER TARIK KOPLING',
            'PER TARIK SEAL HORIZONTAL',
            'PER TARIK SEAL VERTICAL JG, PL-98,10; DK-2,26; DL-',
            'PER TEKAN SS 3MMX14MMX20MMX50MM',
            'PER TEKAN BLOCK UHT SS PL-50; DD-14,5; DK-1,5; DL-',
            'PER TEKAN DAN KNOP',
            'PER TEKAN FILLING JV02 UK. P: 65 MM, OD: 12 MM, ID',
            'PER TEKAN HORIZONTAL (STEEL 3MMx12,5MMx18,5MMx40MM',
            'PER TEKAN HORIZONTAL JELLY GUM ALUNG',
            'PER TEKAN HORIZONTAL KJT',
            'PER TEKAN HORIZONTAL MASEMA',
            'PER TEKAN IMPORT STEEL 2.5MMX15MMX23MMX90MM JN',
            'PER TEKAN IMPORT - STEEL , PL-90; DD-15; DK-2,5; D',
            'PER TEKAN MESIN C5, PL-58,22; DD-40,27; DK-5,12; D',
            'PER TEKAN MESIN C5/C4, PL-50; DD-17,5; DK-1,5; DL-14,50; L-8 (UHT JG)',
            'PER TEKAN MESIN STICK, PL-35,36; DD-11,71; DK-3; D',
            'PER TEKAN PL-72,24; DD-25,27; DK-6,27; DL 37,80; L',
            'PER TEKAN PRESSAN P.6CM X L.3CM X D.2,2CM',
            'PER TEKAN PRESSAN, PL-51,02; DD-14,95; DK-3,02; DL',
            'PER TEKAN SEAL HORIZONTAL',
            'PER TEKAN STEEL 1.5x13x16x40mm',
            'PER TEKAN STEEL 3x12.5x18x45mm 7 Lilitan',
            'PER TEKAN STEEL 4mm x 18,5mm x 26,4 x 61mm',
            'PER TEKAN STEEL, PL-60,76; DD-18,52; DK-4,04; DL-2',
            'PER TEKAN STEEL, PL-60; DD-18; DK-4; DL-26; L-6',
            'PER TEKAN TOZEN MESIN ES SALJU, PL-68; DD-9,39; DK',
            'PER TEKAN VERTICAL UK. P: 2,7 CM, DL: 2 CM',
            'PER TEKAN, PL-61,32; DD-22,02; DK-3,95; DL-29,97;',
            'PER TEKAN, PL-72,24; DD-25,27; DK-6,27; DL-37,80;',
            'PER TEKAN, PL-90,04; DD-16,02; DK-2,61; DL-29,70;',
            'PER TOZEN KLEP',
            'PHOTO SENSOR BR100 - DDT AUTONICS KOREA',
            'PIPA SANITARY 25MM (1 INCH)',
            'PIPA SANITARY 3/4 INCH',
            'PIPA SANITARY 38MM/1.5 Inch',
            'PIPA UK 3/4 INCH PVC',
            'PISAU CARTON SEALER',
            'PISAU PAVO 120 CR P:250cm',
            'PISAU POUCH FULL AUTO 82mm x 23T x 50mm',
            'PISAU SISIR PAVO 120CR BAUT TENGAH',
            'PISAU TUNGTUNG (AUTOCUP TANGGUNG 10 LUBANG)',
            'PISAU ZIGZAG UK. 200',
            'PISTON CYLINDER PUMP',
            'PISTON SYLINDER PUMP TJM',
            'PITA EXPIRE DATE LC1*',
            'PLAT BAUT PRINT HEAD 2 LINE HP-241',
            'PLAT SILICONE RUBBER (5MMX25MMX70MM)',
            'PNEUMATIC COMPONENTS E-MC PRESSURE 0,15-0,8 MPA IS',
            'POTENSIO 100K OHM',
            'POWER SUPPLY 220 VAC 12 VDC 5A',
            'POWER SUPPLY FIX TYPE S82Y - FSC150DIN',
            'POWER SUPPLY SPA 100 24',
            'POWER SUPPLY SPA-050-24',
            'POWER WINDOW SWITCH 0501W',
            'PRESSAN VERTICAL',
            'PRESSURE CONTROL SWITCH SNS - C110 X',
            'PROXIMITY PR12-4DN SENSOR AUTONICS',
            'PROXIMITY SENSOR (AUTONICS PRL12 2DN)',
            'PROXIMITY SENSOR AUTONICS PS12-4DN',
            'PROXIMITY SENSOR INCHAUTONICS PRL12 4DNINCH',
            'PROXIMITY SENSOR PR12-2DN MERK AUTONICS',
            'PULLEY TYPE A. ID:1 inch OD:6 inch DOUBLE',
            'PUSH BUTTON CR 254 A0 HANYOUNG',
            'RANTAI N40',
            'RANTAI NO.50 SINGLE',
            'RANTAI NO.60 SINGLE',
            'RED SEAL CHECKER / MGC',
            'SILICONE RED HIGH TEMPERATURE',
            'REDUCER 1 1/2 INCH X 1/2 INCH GALVANIS',
            'REDUCER 1 1/4 INCH X 1/2 INCH GALVANIS',
            'REDUCER 1 1/4 X 1 1/2 INCH SS',
            'REDUCER 2 INCH X 1 1/2 INCH SS 201',
            'REDUCER 2 INCH X 1/2 INCH PVC',
            'REDUCER 2 X 1 1/2 INCH SS',
            'REDUCER 3 INCH X 1 1/2 INCH PVC',
            'REDUCER 8 INCH X 5 INCH PVC',
            'REDUCER UK 1 1/4 INCH - 1 INCH',
            'REGULATOR 1 TABUNG DRAT 3/8 INCH',
            'REGULATOR KOGANEI R600-4 83MPA',
            'REGULATOR R3000 MERK CKD',
            'RELAY 24-240VAC SSR 10 DA',
            'RELAY BENTELY SSR ST5-5DD INPUT 24VDC',
            'RELAY FOTEX SSR-20 DA',
            'RELAY FOTEX SSR-40 DA',
            'RELAY LY2N 220V AC',
            'RELAY LY4N 220 AC',
            'RELAY LY4N 24V DC',
            'RELAY MY2N 220 VAC',
            'RELAY MY2N 220V AC',
            'RELAY MY2N 240 DC',
            'RELAY MY2N 24V DC',
            'RELAY MY4N 24VDC',
            'RELAY OMRON LY2 DC',
            'RELAY LY2N 24V DC',
            'RELAY OMRON MK2P-I 220V AC 8 KAKI',
            'RELAY OMRON MK2P-N 220VAC 8 KAKI',
            'RELAY OMRON MK2P-N 24 VDC 8 KAKI',
            'RELAY OMRON MKS2P 250VAC',
            'RELAY SSR 24-240VAC 20A',
            'RESISTOR 2W 1 OHM',
            'ROD END M8x125',
            'ROLL PRESS MC Jelly STICK ATAS+BAWAH',
            'ROLL PRESS MC JELLY STICK BELAKANG',
            'ROLLER PLASTIK STAINLESS',
            'RUBBER KOPLING',
            'RUBBER ROLL CONVEYOR + BUSSHING',
            'RUBBER SEAL MC JELLY STICK',
            'RUMAH BEARING 6206',
            'RUMAH TOZEN POMPA INLET',
            'SAKLAR DOUBLE',
            'SAKLAR SINGLE',
            'SAMBUNGAN MATA RANTAI UK. 50 1WBA 1PIN SS',
            'SAMBUNGAN MATA RANTAI UK. 40 SS',
            'SAMBUNGAN MATA RANTAI UK. 60 SS',
            'SAMBUNGAN MATA RANTAI UK. 60 1BA 1PIN SS',
            'SARINGAN / KARUNG HITAM',
            'SARINGAN / KARUNG PUTIH',
            'SCOTCH BRITE',
            'SCOTCH BRITE KAWAT',
            'ORING FLANG SILINDER ( HITAM ) UK 3 X 45',
            'ORING NBR 90 10,5 X 2,62',
            'ORING SILICONE RED 29,51 X 5,3',
            'SEAL BULAT MESIN JELLVIT',
            'SEAL EXPIRE SALJU',
            'SEAL FERULLE 1 INCH',
            'SEAL FERULLE 1/2 INCH',
            'SEAL FERULLE 3/4 INCH',
            'SEAL FERULLE 1,5 INCH',
            'SEAL FERULLE 2 INCH',
            'SEAL FILLING VALVE',
            'SEAL KIT NOORGREEN QA/8125/50',
            'SEAL KIT NORGREN QA/8032/00',
            'Seal kit norgren QA/8100/00',
            'ENDSEAL PRESSAN HORIZONTAL 110 MM (ES SALJU)',
            'ENDSEAL PRESSAN HORIZONTAL 150 MM (JELY GUM)',
            'ENDSEAL PRESSAN VERTICAL UKURAN 180 (MESIN JG & SALJU',
            'SEAL PRESSAN VERTIKAL UK. 150MM (JELY GUM)',
            'SEAL SILICONE 49,5 x 31,5 x 17 MM - STICK',
            'SEAL TAPE RYUICHI 12MM X 0,75 MM X 10M',
            'SEAL TEFLON PISTON UK 40 MM',
            'SEAL UNION JOINT',
            'SEAL/ORING FLANGE CYLINDER UK 3x45 (HITAM)',
            'ORING GASKET 2 INCH',
            'SIKRING TANCAP BESAR 15A',
            'SIKRING TANCAP KECIL 15A',
            'SELANG ANGIN PU 10 X 6,5 MM',
            'SELANG ANGIN PU 4 X 2,5 MM',
            'SELANG ANGIN PU 4 X 6 MM',
            'SELANG ANGIN PU 5 X 10 MM',
            'SELANG ANGIN PU 5 X 8 MM',
            'SELANG ANGIN PU 6 MM X 4 MM',
            'SELANG ANGIN PU 8 X 12MM',
            'SELANG ANGIN PU 8,5 X 14MM',
            'SELANG ANGIN UK 16 X 12MM',
            'SELANG BENANG 3/8 INCH',
            'SELANG BENANG NYLON 1 INCH',
            'SELANG FLEKSIBLE 45 cm',
            'SELANG FOOD GRADE 1INCH KAWAT',
            'SELANG FOOD GRADE 3/4 INCH KAWAT',
            'SELANG FOOD GRADE UK. 1INCH BENANG',
            'SELANG KAWAT 1 1/4 INCH',
            'SELANG KAWAT 1 INCH',
            'SELANG KAWAT 3/4 INCH',
            'SELANG KAWAT SPIRAL UK 1INCH',
            'SELANG KAWAT UK 1/2 INCH',
            'SELANG KAWAT UK. 3/8 INCH',
            'SELANG NYLON 12 X 9 MM',
            'SELANG NYLON UK 16MM X 13MM',
            'SELANG PU DIA, 12MM X 8MM',
            'SELANG PU DIA, 6 MM X 4 MM',
            'SELANG PU DIA, 8 MM X 5 MM',
            'SELANG PU dia: 16MM x 12 MM',
            'SELANG SILICONE OD: 6MM X ID: 4MM',
            'SELANG SILICONE UK. 12 X 16MM',
            'SELANG SILICONE UK. 8 X 12MM',
            'SELECTOR SWITCH CRSL-253A1, 250VAC 5A, MERK HANYOU',
            'SELECTOR SWITCH SINGLE / 1 POSISI',
            'SELECTOR SWITCH ZB2-BE101C, MERK EWIG',
            'SELENDANG BAN F 16',
            'SELENDANG F 20',
            'SELENOID FOR PNEUMATIC E.MC 220V AC 4.0VA',
            'SELENOID SF410IP',
            'SELENOID SF5101-JP',
            'SELENOID VALVE 5/2 PORT 1/2 Inch 220V',
            'SELENOID VALVE MV7 451587',
            'SELENOID VALVE MV8 451626',
            'SELENOID VALVE SMC SY5120-5D-01',
            'SELENOID VQ21A1-5G-C6',
            'SELENOID VQ21A1-5G-C8',
            'SELONGSONG HEATER + SPIRAL',
            'SENSOR AUTONICS FD-620-10 PROXIMITY SWITCH',
            'SENSOR GL-518NO (MESIN SEAL CARTON)',
            'SENSOR MESIN T JET',
            'SENSOR NBSKK',
            'SENSOR SICK GTE6 N1211',
            'SENSOR T JET TYPE GL-S18N0',
            'SERVICE BOX HOT CODING',
            'Service pressan vertical',
            'SERVICE SEAL PRESSAN HORIZONTAL 150 MM',
            'SERVICE SEAL PRESSAN JELLY GUM',
            'SERVO CAM B (CSB)',
            'SERVO CAM D (CSD)',
            'SET MATA GERINDA BATU SHANK 3MM',
            'SHIELD UP(KERAMIK) PLASMA PT31',
            'SILENCER 1/4 INCH',
            'SILENCER 4/8 Inch',
            'SILENCER 10A 3/8 Inch',
            'SILENCER 6A 1/8 Inch',
            'SILICONE RUBBER 5 MM x 2 MM (ALU) x 18,5 MM x 100',
            'Silicone Rubber Red (plat aluminium) 71,5mm x 25mm',
            'SILICONE RUBBER ROBO KIDZ',
            'SILICONE RUBBER UK 3MM X 500MM X 1000MM',
            'SILICONE RUBBER UK 4MM X 50MM X 100MM',
            'SILICONE RUBBER UK 5MM X 50CM X 100CM',
            'SILICONE RUBBER UK. 6 MM X 50 MM X 100CM',
            'ORING WHITE SILICONE ID: 51,8 MM, OD: 58,8 MM, CS: 3,5 MM (FP)',
            'SILICONE SEALENT DEXTONE',
            'SILICONE SPRAY MERK SPRINT',
            'SNAPRING R-30',
            'SOCK 1 INCH PVC',
            'SOCK 1/2 INCH PVC',
            'SOCK 2 1/2 INCH PVC',
            'SOCK 2 INCH PVC',
            'SOCK 3 INCH PVC',
            'SOCK 3/4 x 1/2 INCH PVC',
            'SOCK 5 INCH PVC',
            'SOCK DRAT DALAM 1 1/2 INCH GALVANIS',
            'SOCK DRAT DALAM 1 1/4 INCH GALVANIS',
            'SOCK DRAT DALAM 1 1/4 INCH SS',
            'SOCK DRAT DALAM 1 INCH GALVANIS',
            'SOCK DRAT DALAM 1 INCH PVC',
            'SOCK DRAT DALAM 1/2 INCH GALVANIS',
            'SOCK DRAT DALAM 1/2 INCH PVC',
            'SOCK DRAT DALAM 1/2 INCH SS',
            'SOCK DRAT DALAM 1/4 INCH SS',
            'SOCK DRAT DALAM 11/2 SS',
            'SOCK DRAT DALAM 2 INCH GALVANIS',
            'SOCK DRAT DALAM 2.5 INCH GALVANIS',
            'SOCK DRAT DALAM 3 INCH GALVANIS',
            'SOCK DRAT DALAM 3/4 INCH GALVANIS',
            'SOCK DRAT DALAM 3/4 INCH PVC',
            'SOCK DRAT DALAM 3/4 INCH SS',
            'SOCK DRAT DALAM 4 INCH PVC',
            'SOCK DRAT LUAR 1 INCH PVC',
            'SOCK DRAT LUAR 2 1/2 INCH PVC',
            'SOCK DRAT LUAR 2 INCH PVC',
            'SOCK DRAT LUAR 4 INCH PVC',
            'SOCKET RELAY MY2N 8 PIN - PYF8A',
            'SOCKET TIMER AUTONICS PG - 08 (8 pin)',
            'SOLAR GENSET',
            'SOLAR PERTAMINA DEX',
            'SOLID STATE RELAY 240V AC 10 AMP',
            'SOLID STATE RELAY KSD240AC8 MERK COSMO',
            'SPROCKET TYPE HS 2500',
            'SPROKET 40 X 15',
            'SPROKET 40 X 20',
            'SPUR GEAR MESIN JG',
            'SPURE GEARS SS DIA. 56,8 x 30MM',
            'SSR 40A KSD240AC8',
            'SSR AUTONICS SRH1-1215-N MERK AUTONICS 24-240V AC',
            'STAIN CLEAN NIKKO STEEL',
            'STARTER PHILIPS S10 - P 4 - 65W',
            'STEKER BROCO',
            'STOP KONTAK 1 TOMBOL',
            'STOP KONTAK 2 TOMBOL',
            'STOP KONTAK ISI 4 BROCO',
            'STRIP HEATER UK. 20 X 250MM, 300W 230V, P. KABEL 3',
            'SURFACE MOUNTING WALL SOCKET',
            'SWITCH OMRON D4MC 5020',
            'SWITCH ON OFF KCD4',
            'SWITCHING POWER SUPLY 24V 5A',
            'TAP 68 90 10',
            'TEE 1 1/2 INCH GALVANIS',
            'TEE 1 1/2 INCH PVC',
            'TEE 1 1/2 INCH SS',
            'TEE 1 1/4 INCH GALVANIS',
            'TEE 1 INCH GALVANIS',
            'TEE 1 INCH PVC',
            'TEE 1 INCH SS',
            'TEE 1/2 INCH GALVANIS',
            'TEE 1/2 INCH PVC',
            'TEE 2 INCH GIV',
            'TEE 2 INCH PVC',
            'TEE 2 INCH SS',
            'TEE 3 INCH GALVANIS',
            'TEE 3 INCH PVC',
            'TEE 3 INCH X 1 INCH PVC',
            'TEE 3 INCH X 3/4 INCH PVC',
            'TEE 3/4 INCH PVC',
            'TEE 3/4 INCH SS',
            'TEE 3/8 INCH SS',
            'TEE 80MM X 40MM / 3 INCH PVC',
            'TEE DRAT DALAM 1 INCH GALVANIS',
            'TEE SANITARY 19MM',
            'TEE SANITARY 316 1" (25MM)',
            'TEE SANITARY 316L DIA 1 1/2 INCH',
            'TEE SEAMLESS SCH40 1 1/2 INCH (PIPA HITAM)',
            'TEFLON HIJAU MESIN EXPIRE DATE CODING',
            'TEFLON MERAH PJG 11.5x4.5CM',
            'TEFLON MERAH UK. 1000 X 1000 X 6 MM',
            'Teflon Merah Uk. 1000x1000x8mm',
            'TEMPERATUR SENSOR TYPE K CABLE 10 M',
            'TEMPERATURE CONTROL (CODING MS 200)',
            'TEMPERATURE CONTROL AX2-1A',
            'TEMPERATURE CONTROL FOTEX MT72 - V',
            'TEMPERATURE CONTROL HANYOUNG FT-C400',
            'TEMPERATURE CONTROL HANYOUNG NUX AF1 PKN1NR07 50 H',
            'TEMPERATURE CONTROLLER T3S - B4RK4C N',
            'TEMPERATURE CONTROLLER TCN4S - 24R',
            'TEMPERATURE E5EM - YR40K MERK OMRON',
            'TEMPERATURE SENSOR RTD PT 100 MAX TEMP. 350 DEG C',
            'TERMINAL BLOCK ISI 24',
            'TERMINAL KERAMIK 15 A',
            'TERMINAL KERAMIK 30 A',
            'TERMINAL ISI 2',
            'TERMINAL KERAMIK 35 A',
            'TERMINAL OVERLOAD MITSUBISHI THN20 15A (12A-18A)',
            'TERMOMETER DIGITAL KSRISCHEFT',
            'THERMAL OVERLOAD SCHNEIDER LRD 08 ( 2,5-4A )',
            'THERMOMETER PAYUNG 300 DEGREE C MEREK ALDO',
            'THINER 1 LITER CAP CEPOT',
            'THINER 5 LITER CAP CEPOT',
            'THREEBOND RED / LEM GASKET',
            'TIMER LADS2 SCHNEIDER 10A',
            'TIMER OMRON 8KAKI TYPE AT8N MERK AUTONICS 100/240V',
            'TIMER OMRON H3G -8C',
            'TIMER TYPE H3CR - F8 OMRON',
            'TIMING BELT 187',
            'TINER',
            'TINTA INK JP-K72',
            'Tinta INK V411-D',
            'TINTA PW-B801+',
            'TINTA SABLON WARNA BLACK MERK TOYO INDO INKS',
            'TOGGLE SWITCH',
            'TOMBOL EMERGENCY',
            'TOMBOL ON OFF KOTAK',
            'TOMBOL TEKAN STOP DARURAT ZB2-BE102C 220V 1A',
            'TOZEN VALVE ATAS',
            'TOZEN VALVE BAWAH',
            'TRAY JELLVIT STAINLESS',
            'TULISAN AIR DINGIN/ AIR PANAS',
            'TUSEN KLEP 2 INCH KUNINGAN',
            'TUSEN KLEP 3 INCH KUNINGAN',
            'Valve Engine 399-181',
            'VAN BELT 1364 X 50',
            'VAN BELT 22-8-700 1422V270 L7208-210 20',
            'VAN BELT A 33',
            'VAN BELT A 56',
            'VAN BELT A 177BLI',
            'VAN BELT A 22',
            'VAN BELT A 24',
            'VAN BELT A 25',
            'VAN BELT A 26',
            'VAN BELT A 27',
            'VAN BELT A 28',
            'VAN BELT A 34',
            'VAN BELT A 35',
            'VAN BELT A 36',
            'VAN BELT A 49',
            'VAN BELT A 50',
            'VAN BELT A 52',
            'VAN BELT A 54',
            'VAN BELT A 76',
            'VAN BELT A 78',
            'VAN BELT A 30',
            'VAN BELT A 70',
            'VAN BELT B 51',
            'VAN BELT B 54',
            'VAN BELT B 72',
            'VAN BELT B 77',
            'VAN BELT B 78',
            'VAN BELT B 85',
            'VAN BELT CARTOON SEALER',
            'VAN BELT GERIGI REFCMF - 6610',
            'VAN BELT GIGI 5 KM (N)',
            'VAN BELT K 26',
            'VAN BELT MOBIL',
            'VAN BELT MOTOR ROLL FILM / MB370',
            'VAN BELT RECMF - 6610 5 E6128-E6129-E6130',
            'VELK BAN',
            'WATER MUR 1/2 INCH SS',
            'WATER MUR 2 INCH GALVANIS',
            'WATER MUR 2 INCH PVC',
            'WATER MUR 2.5 INCH GALVANIS',
            'WATER MUR 3 INCH PVC',
            'WATER MUR 4 INCH PVC',
            'WATERMUR SANITARY 2 INCH (50MM)',
            'WD 40',
            'WIFER KACA PS 220 (FUSO)',
            'WIRE MESH',
            'Y STRAINER 2 INCH KUNINGAN',
            'AC AUTOMATIC VOLTAGE REGULATOR MODEL AVR 1000 (STABILIZER)',
            'AC SERVO MOTOR 400W PANASONIC MHMD 042G1U',
            'ACTUATOR KIT 1/2 INCH UNTUK ROBOKIDZ 2000 A MERK KANGSAITE',
            'ADJUSTER KAKI CONVEYOR',
            'AIR CYLINDER AIRTAC SGC 125 X 50',
            'AIR CYLINDER CQ2B50-50DZ MERK SMC',
            'AIR CYLINDER MSD 40 X 10',
            'AIR FILTER KOGANEI 600-04 REGULATOR LUBRICATOR',
            'AIR FILTER REGULATOR DOUBLE TEKIRO INLET 1/2 INCH',
            'AIRTAC FRL COMBINATION AFR 2000',
            'AIRTAC SOLENOID VALVE 4V410-15 DC24V',
            'ALARM SENSOR MESIN DATE CODING',
            'AMPLAS 240',
            'AMPLAS 400',
            'AMPLAS 600',
            'AMPLAS CW 1000',
            'ARANG KARBON BULAT',
            'ARM FILLING ROBOKIDZ',
            'ARM PRESSAN JG',
            'AS BUSHING MH05',
            'AS GEAR PANJANG',
            'AS KONEKTOR GEAR',
            'AS KUNINGAN 13/4 x 95',
            'Sock 3/4 Inch PVC AW',
            'BALING-BALING SHAFT MESIN JG',
            'BALL VALVE 3/4 INCH PVC AW',
            'BALL VALVE 3 INCH PVC',
            'BAN ARTCO MATI DIAMETER 34CM',
            'BAN DALAM 900 GT',
            'BAN FORKLIFT',
            'BAN FORKLIFT MATI MERK ASENDO UK 5.00 - 8',
            'BAN FORKLIFT MATI MERK ASENDO UK 6.50-10',
            'BAN FORKLIFT MATI MERK BRIGHTSTONE UK 6.50-10',
            'BAN GOTROK BATUBARA',
            'BAN LUAR 1000',
            'BAN LUAR 650',
            'BANDUL KOPLING',
            'BANTALAN PER',
            'BANTALAN TEFLON',
            'BATERAI CE 1220',
            'BATERAI PANASONIC CR 1220 LITHIUM 3V',
            'BATERAI PANASONIC CR2032 LITHIUM 3V',
            'BATU GERINDA DUDUK 150 X 19 X 31 GREAT',
            'BAUT JF 6 X 20 MM SS',
            'BAUT JF SS UK. 1/4 X 1/2 INCH',
            'BAUT NYLON TATAKAN MOULD 15MM X 30MM',
            'BEARING 207 51207 NSK',
            'BEARING 32209',
            'BEARING 51105',
            'BEARING 6001',
            'BEARING 6001 2NSE',
            'BEARING 6006',
            'BEARING 6006 2RSR',
            'BEARING 6006 DU',
            'BEARING 6006 LU',
            'BEARING 6006 ZZ',
            'BEARING 6007 2 RSR',
            'BEARING 6007 NTN ZZ',
            'BEARING 6008',
            'BEARING 6008 2RSR',
            'BEARING 6009 ZZ',
            'BEARING 6014 DU',
            'BEARING 6014 NTN',
            'BEARING 608 RS',
            'BEARING 608 ZZ',
            'BEARING 6207',
            'BEARING 6207 LLB',
            'BEARING 6300',
            'BEARING 6301 2RS',
            'BEARING 6301 ZZ',
            'BEARING 6303',
            'BEARING 6303 2RS',
            'BEARING 6303 LLU',
            'BEARING 6304 2RS',
            'BEARING 6304 ZZ',
            'BEARING 6307',
            'BEARING 6309 NSE',
            'BEARING 6310 2RSR',
            'BEARING 6804 Z',
            'BEARING 6901 ZZ NTN',
            'Bearing 6904',
            'BEARING 696 SKF',
            'BEARING ARTCO',
            'BEARING FOR INDEXING GEARBOX - CHINA',
            'BEARING HRB 30208',
            'BEARING HRB 30209',
            'Bearing LFR50',
            'BEARING LMF 20 UU',
            'BEARING NTN 32022',
            'BEARING UC 206',
            'BEARING UC 208-24',
            'BEARING UC 208-24',
            'BEARING UC 210',
            'BEARING UC 211-32 (2 INCH)',
            'BEARING UCP 205 - 16 PILLOW BLOCK',
            'BEARING UCT 204',
            'BEARING UCT 205',
            'BEARING UCT 206',
            'BELT CONVEYOR',
            'BELT MOVING',
            'BELT RUBBER LINE 2 HIGH SPEED F SEQWT 5.550 X 90 ENDLESS',
            'BELT RUBBER LINE 3 HIGH SPEED F SEQWT 5.950 X 90 ENDLESS',
            'BELT RUBBER LINE 4 HIGH SPEED F SEQWT 5.150 X 90 ENDLESS',
            'BELT RUBBER LINE 4 HIGH SPEED F SEQWT 6.350 X 90 ENDLESS',
            'BELT RUBBER LINE 5 HIGH SPEED F SEQWT 6.750 X 90 ENDLESS',
            'BENSIN FORKLIFT',
            'BIG M ANALOG PANEL METER 600/5 A',
            'BOHLAM DESKBORARD',
            'BOHLAM INDIKATOR',
            'BOHLAM LAMPU TEMBAK 150 WATT',
            'BOSS PER',
            'BOX HOT CODING',
            'BRACKET HEATER BESAR FL',
            'BRACKET HEATER KECIL FL',
            'BRACKET KUPINGAN RANTAI UK. 50',
            'BUSHING AS CENTER BAJA',
            'BUSHING AS CENTER SS',
            'BUSHING BEARING 6303 JG',
            'BUSHING KIT',
            'BUSHING MEKANIK PISAU',
            'BUSI BOSCH FORKLIFT',
            'BUSI FORKLIFT',
            'CAP CARBURATOR',
            'CARBON BRUSH 4 X 4',
            'CARBON BRUSH BULAT (BENTUK TABUNG)',
            'CARBON BRUSH CB 203 A',
            'CARBON BRUSH CB 459',
            'CARBON BRUSH CB 64 A',
            'CARBON BRUSH HORIZONTAL 04',
            'CASTROL LONGTIME PD2',
            'CAT ANTI PANAS 400 DERAJAT CELCIUS WARNA SILVER',
            'CAT BATU CANDI MERK PROPAN STONE CARE WARNA BLACK',
            'CAT BESI MERK AVIAN SUPER WHITE',
            'CAT BESI MERK NIPPON PAINT NP 610 BRIGHT BLUE',
            'CAT BESI MERK NIPPON PAINT NP 622 GREY',
            'CAT BESI MERK NIPPON PAINT NP 631 WARNA COCO BROWN',
            'CAT BESI MERK NIPPON PAINT NP 663 WARNA COKLAT',
            'CAT BESI MERK NIPPONT PAINT BS9102 SUPER WHITE',
            'CAT BESI MERK YOKO BLUE WARNA 779 SUNFLOWER',
            'CAT BESI MERK YOKO BLUE WARNA SUPER BLACK',
            'CAT BESI NIPPON PAINT NP 649 WARNA BLUE BELL',
            'CAT BESI NIPPON PAINT NP 680 SHINE',
            'CAT GENTENG MERK NIPPON PAINT WARNA PUTIH',
            'CAT KOLAM GLOTEX 71036',
            'CAT LAPANGAN MERK PROPAN WARNA ORANGE',
            'CAT MERK PROPAN GEMINI WARNA KUNING 0,9L',
            'CAT PILOK BESI MERK SUZUKA SC-135 WARNA METALICA SILVER',
            'CAT TEMBOK MERK AVITEX WARNA PUTIH',
            'CATRIDGE HEATER + NEPEL 500W 220V, UK 16,1 x 155M KABEL 25CM',
            'CETEKAN ON/ OFF',
            'CHNT CONTROL DEVICE ELEKTROMAGNETIK KONTROL KECEPATAN ELECTROMOTOR JD1A-90 AC 220 V/ 50 HZ, DC 8A, DC 90 V, 75-90 KW',
            'CINCIN CARBON KUNINGAN',
            'CLEANER PRINTFLEX / UNIVERSAL CLEANER',
            'COLLECT 2,4',
            'CORONG CENTER UK. 100 - JG',
            'CORONG JELLY GUM 100 MM',
            'CORONG STICK YOGU UK. 52',
            'Coustic / Soda Api',
            'CURRENT TRANSFORMERS MSQ-30 SERIES 100/5 A FORT',
            'CURRENT TRANSFORMERS MSQ-60 SERIES 600/5 A FORT',
            'DANA PAINT HARDENER LEM 0,3 LITER',
            'DIGITAL OUTPUT MODULE COMPONENT PLC',
            'DIGITAL PRESSURE DP-102 MERK PANASONIC',
            'DONGKRAK 30 TON',
            'DOP 1 INCH GALVANIS',
            'DOP 1 INCH PVC',
            'DOP 2 INCH PVC',
            'DOP 3 INCH PVC',
            'DOP 3/4 INCH PVC',
            'DOP 4 INCH PVC',
            'DUDUKAN FILTER SOLAR ATAS PS.120',
            'DUDUKAN HEATER STICK',
            'DUDUKAN KABIN KARET',
            'DUDUKAN KABIN PINTU STOPPER HEPPER',
            'DUDUKAN KARAKTER NY 808',
            'DUDUKAN RELAY 8 PIN MERK EWIG 36 X 80 MM DYF 14 A',
            'DUDUKAN RELAY 8 PIN PS-08 2-M4X20MM',
            'DUDUKAN RELAY DTF14A 36X68MM MERK EWIG',
            'DUDUKAN RELAY PTF14A 36X68MM',
            'DUDUKAN SENSOR FIBER OPTIK',
            'ELBOW 1 1/4 INCH SS',
            'ELBOW 2 1/2 INCH PVC',
            'ELBOW DRAT 1/2 INCH SS',
            'ELCO 1000UF 10V',
            'ELCO 33UF 450V',
            'ELCO 470UF 25V',
            'ELCO 470UF 35V',
            'ELECTRODE HOLDER PS-3S',
            'ELEKTRODA TIP PLASMA CUT 4O SHORT',
            'FAN AC AXIAL BLOWER 120 X 120 X 38MM 220V AC',
            'FAN NMB MODEL 4715 KL-05W-B40 (KIPAS)',
            'FAN NMB-MAT MINEBEA 4710KL-05W-B4912025 12CM 24VDC 0.29A',
            'FERULLE 2 INCH',
            'FERULLE 316 1 1/2 INCH',
            'Ferulle Sanitary 25MM',
            'FERULLE SANITARY 316L 1 1/2 INCH',
            'FILTER BENSIN F1 DAN F3',
            'FILTER OLI C - 1104',
            'FILTER OLI C 1007',
            'FILTER OLI C 1115 F1',
            'FILTER OLI C 1539 F3',
            'FILTER OLI C-1004',
            'FILTER OLI C-1012',
            'FILTER OLI C-1142',
            'FILTER OLI POE074',
            'FILTER SOLAR ATAS FC-1003',
            'FILTER SOLAR ATAS FC-1004',
            'FILTER SOLAR ATAS FC-1005',
            'FILTER SOLAR ATAS FC-1012',
            'FILTER SOLAR BAWAH F-1002',
            'FILTER SOLAR BAWAH ME121653',
            'FILTER SOLAR BAWAH SF-1004',
            'FILTER UDARA A-1007',
            'FILTER UDARA A-1093',
            'FILTER UDARA F1 (A 1014)',
            'FILTER UDARA F3 ( D821575)',
            'FILTER UDARA FUSO',
            'FITTING APC 16',
            'FITTING APC 16-01',
            'FITTING APE 10',
            'FITTING APE 12',
            'FITTING APE 16',
            'FITTING APE 8-02',
            'FITTING APL 04-01',
            'FITTING APL 16',
            'FITTING REDUCER 12-10',
            'FITTING REDUCER 12-16',
            'FITTING REDUCER 8-6',
            'FITTING Y 6-4',
            'FLANGE 1 INCH SS',
            'FLANGE 2 INCH',
            'FLANGE 4 INCH SS',
            'FLASER',
            'FLASH BAND 2 INCH',
            'FLOATLESS OMRON TYPE 61F-G-AP 2 RELAY',
            'FLOATLESS RELAY LEVEL SW TYPE AFR-1 220V AC 50/60 HZ',
            'FRONT RUBBER ROLLER',
            'FUSE 1 AMP',
            'FUSE 4 AMP',
            'FUSE 5 AMP',
            'FUSE KERAMIK 2A (R015)',
            'GASKET 0,5 X 1000 X 1000',
            'GEAR PRESSAN',
            'GEAR/ SPROKET TEFLON 25 MATA DIAMETER AS 24MM RS50',
            'GEMBOK',
            'GEMBOK LEHER PANJANG UK. 30MM',
            'HALBASIT BELT 1030 X 200',
            'HALBASIT BELT 1380 X 250',
            'HALBASIT BELT 1750 X 250',
            'HANDLE KACA',
            'HEATER 1500W 220V, DIA 19MM X 350MM, KABEL 25 CM',
            'HEATER 150W 220V, 51,04MM X 10,22MM',
            'HEATER 2500W 220V, DIA 19 MM X 350 MM, KABEL 25 CM',
            'HEATER 300W 220V, 89,1MM X 16,1MM',
            'HEATER 400W 220V, 160MM X 15,60MM',
            'HEATER 40W 110V, 30MM X 10MM',
            'HEATER 500W 220V, 150MM X 12MM',
            'HEATER 500W 220V, 80MM X 12MM',
            'HEATER 500W 230V, 160CM X 14,61MM',
            'HEATER 600W 220V, 230MM X 17,1MM (MS SHRINK)',
            'HEATER BULAT 300W 230V',
            'HEATER CATRIDGE 500W 220V, 160MM X 16MM',
            'HEATER ELEMENT 150W 220V, 81,26MM X 6,60MM',
            'HEATER ELEMENT 150W 230V, (88MM X 7MM)',
            'HEATER ELEMENT 300W 230V, 70MM X 9,5MM',
            'HEATER ELEMENT 400W 220V, (80MM X 10MM)',
            'HEATER ELEMENT 500W 220V, (160MM X 12M)',
            'HEATER ELEMENT HEATER KAWAT',
            'HEATER ELEMENT ST11209 150W 22V, 8MM X 6MM',
            'HEATER ELEMENT TH 210 125W 230V, 4CM X 7MM',
            'HEATER KACA 1000W 220V',
            'HEATER STRIP 160W 110V, 150MM X 24MM - JG TJM',
            'HEATER TUBULAR STRAIGHT 400W 220V, Ø7,90MM X 42 CM',
            'HIGH TEMP SILICONE MERK THREEBOND 75GR',
            'HOSE NAPPLE 3/4 INCH SS',
            'INK JET PRINTER MERK ELFIN1S',
            'INVENTER DELTA VFD-007Kw',
            'INVERTER CONVEYOR',
            'INVERTER FUJI ELEKTRIK FRENIC MINI FRN0006 C25-7A',
            'JARUM LAS ARGON 2,4 MM',
            'KABEL HEATER 2 MM',
            'KABEL HEATER 3 MM',
            'KABEL INJEKTOR',
            'KABEL MASSA',
            'KABEL MIKA',
            'KABEL NYM 4 X 4 - AIR NEV',
            'KABEL THERMO COUPLE 10 METER TYPE FT-K/J-M6',
            'KABEL TIES 150 MM',
            'KABEL TIES 300 MM',
            'KACA LAS RIBEN HITAM NO.10',
            'KACA SPION FUSO',
            'KACA SPION TURBO',
            'KAIN MAJUN',
            'KANVAS REM ( BRAKE SHOE)',
            'KANVAS REM RCA MB 162517',
            'KANVAS REM TURBO',
            'KAPASITOR 16 Uf',
            'KAPASITOR 2,5 UF',
            'KAPASITOR 20 uF',
            'KAPASITOR 300MFD 125V AC',
            'KAPASITOR 4 UF 250 VAC',
            'KAPASITOR 400/450V AC 18 MIKRON F',
            'KARABINER SEGITIGA',
            'KARAKTER GARIS MIRING ( / )',
            'KARET STOPPER STOPPER HELPER - TURBO',
            'KARPET LUMPUR',
            'KAWAT LAS ARGON 0,8',
            'KAWAT LAS ARGON 1,5',
            'KAWAT LAS ARGON 2,0',
            'KAWAT LAS TUNGSTEN 2,4 MM MERK WELDCRAFT',
            'KAWAT SELING 5MM 12X7',
            'KERAMIK/SWIRL RING PLASMA 40 SHORT',
            'KLAKSON',
            'KLEM KAWAT 1 1/2 INCH',
            'KLEM SELANG 1/2 INCH',
            'KLEMAN ACCU',
            'KONTAKTOR LC1D25Q7 40A SCHNEIDER',
            'KONTAKTOR LC1D32M7 50 A SCHNEIDER',
            'KONTAKTOR LC1DT32M7 220V AKSESORIS PENGAMAN (BAGIAN PANEL LISTRIK)',
            'KONTAKTOR MAGNET MERK MITSUBISHI TIPE S-T10 20A',
            'KOTAK OBAT',
            'KRAN 2 INCH PVC',
            'KRAN 3/4 SS',
            'KRAN VALVE 1 1/4 INCH KUNINGAN',
            'KRANZ 1/2 INCH GALVANIS',
            'KUAS 2,5 INCH',
            'KUAS 3 INCH',
            'LAHER / BEARING KNALPOT',
            'LAMPU BOX DNY91',
            'LAMPU LED 18 WATT  PHILIPS + MIKA (ISI 2)',
            'LAMPU LED 19 WATT',
            'LAMPU NEON LED 18 WATT',
            'LAMPU NEON PHILIPS 18W',
            'LAMPU SENT',
            'LAMPU SOROT / LAMPU TEMBAK LED HOKISTAR 50W',
            'LAMPU TEMBAK LED 100W',
            'LAMPU TEMBAK LED 200W',
            'LAMPU TL PHILLIPS 18 WATT',
            'LAMPU ULTRA VIOLET MERK VIDUA S950RL-HO',
            'LAMPU VESTA LED 50W',
            'LANGSOL',
            'LIMIT SWITCH 16A 250V AC RV-166-1C25',
            'LIMIT SWITCH CZ-7310',
            'LIMIT SWITCH Z - 15GW2-B',
            'LIMIT SWITCH Z - 15GW-B',
            'LIMIT SWITCH Z - 15HW78-B',
            'MAGNETIC SWITCH C10 3,6A 400V',
            'MATA BOR 10 MM',
            'MATA BOR 12 MM - BOSCH',
            'MATA BOR 18 MM',
            'MATA BOR 18 MM - MERK ALDO',
            'MATA BOR 19MM',
            'MATA BOR 5 MM',
            'MATA BOR 8 MM MERK BOSCH',
            'MATA BOR NACHI 2,5 INCH',
            'MATA BOR NACHI 3,5 INCH',
            'MATA BOR UK. 3,5 MM',
            'MATA BOR UK. 8 MM',
            'MATA GERGAJI BESI MERK SANDFLEX 12 INCH/300MM',
            'MCB 1 PHASE 16 A',
            'MCB 1 PHASE 25 A',
            'MCB C16 DOMF01116 230V MERK SCHNEIDER',
            'MCB C16 NXB-63 3P',
            'MCB C25 DOMF01125 230V MERK SCHNEIDER',
            'MCB C32 DOMF01132 230V MERK SCHNEIDER / mcb 3 phase',
            'MCCB NM1-63S/3300 50 A',
            'MECHANICAL SEAL BESAR',
            'MECHANICAL SEAL KECIL',
            'MECHANICAL SEAL MERK POMPA CNP SEAL CDLF 32-85 MECHANICAL SEAL SHAFT POMPA NJK-22',
            'MECHANICAL SEAL SEA AS 14 MM - LOWARA',
            'MECHANICAL SEAL SIC',
            'MECHANICAL SEAL TYPE MS-12 / DB125',
            'MECHANICAL SEAL UHT',
            'MICRO SWITCH CHINT YBLXW-6/11BZ',
            'MIKA BOX LED',
            'MIKA BOX PANJANG',
            'MIKA KODOK',
            'MIKA LAMPU SENT',
            'MODULE / PCB BLOCK CONTROL 24V DC',
            'MORTISE DOOR LOCK',
            'MOTOR 220V 25W 1300RPM PEEI MOGER M-4IK25N-C',
            'MOTOR CIRCUIT BREAKER EZC100B3050',
            'MOTOR CIRCUIT BREAKER EZC100F3080',
            'MUR DUDUKAN PER STICK',
            'NOZLE TIP PLASMA CUT 40 SHORT',
            'NYLON GUIDE RAIL 12CJD',
            'OIL SEAL RST 45-72-8',
            'OIL SEAL TC 12-21-7',
            'OIL SEAL TC 12-24-7',
            'OIL SEAL TC 12-28-7 NOK',
            'OIL SEAL TC 140 X 170 X 15',
            'OIL SEAL TC 16-30-7',
            'OIL SEAL TC 17-30-7',
            'OIL SEAL TC 20-35-7',
            'OIL SEAL TC 20-36-7',
            'OIL SEAL TC 25-40-7',
            'OIL SEAL TC 30-50-10',
            'OIL SEAL TC 45-65-10',
            'OIL SEAL TC 50-80-10',
            'OIL SEAL TCY 9-21 6X8',
            'OLI GARDAN SAE 140',
            'OLI GEARBOX SAE 40',
            'OLI GEARBOX SAE 60',
            'OLI GEARBOX SAE 90',
            'OLI MESIN (WIN) SAE 40',
            'OLI MESIN FORKLIFT',
            'OLI PORSNELING',
            'Oring putih masema',
            'ORING RED SILICON 19 X 2,65MM',
            'Oring Red Silicone 48,7 X 1,8mm',
            'Oring Red Silicone 54,5 X 3,55mm',
            'Oring Red Silicone 59,6mm X 64,6mm X 2,5mm',
            'Oring Red Silicone 63 X 2,65mm',
            'ORING RED SILICONE 86 X 3,55 MM',
            'ORING RED SILICONE AS-227 CS: 3,53 ID: 53,57 OD: 60,63 MM',
            'ORING SILICONE ID: 30 MM X 4,5 MM',
            'ORING WHITE SILICON 12,5 X  1,8MM',
            'Oring White Silicone Dia 41,6 X 49 X 3,7mm',
            'Oring White Silicone ID: 41,7mm, OD:48,7mm, CS: 3,5mm',
            'OVERLOAD GV3M80/ 56-80A',
            'OVERLOAD LRD10 4-6 AMP BAGIAN PANEL LISTRIK/ AKSESORIS PENGAMAN',
            'OVERLOAD RELAY 1-1,6 AMP LRD06',
            'PAKING GABUS 3X90X90 - HITAM',
            'PANEL METER 500V SF-96 FORT',
            'PANEL VOLTMETER FORT 200 AMP MODEL SF-96',
            'PEEI MOGER M-2DK6N-F18 6W 24VDC, 1800 RPM DM-4522',
            'PEGAS VIBRATING',
            'PELAMPUNG CATRIDGE',
            'PEMADAM ( APAR )',
            'PENSIL TUKANG',
            'PER DUDUKAN BUSHING MESIN STICK',
            'PER PISAU JG, PL-36,04; DD-5,03; DK-1; DL-9; L-37',
            'PER SS DD: 14 MM, P: 50 MM, TINGGI: 0,5 MM (C6)',
            'PER STAINLESS DIA DALAM 9MM PANJANG 50MM (C6)',
            'PER TARIK DATE CODING (JG) OD: 4,5 MM, ID: 3,5 MM, P: 19 MM, KAWAT 0,5 MM',
            'PER TARIK ENCODER',
            'PER TARIK EXPIRE P: 29 MM, DL: 5,6 MM',
            'PER TARIK HORIZONTAL, PL-138,36; DK-2,81; DL-22,01',
            'PER TARIK KOPLING, PL-142,64; DK-1,58; DL-18,25',
            'PER TARIK MESIN DATE CODING (JG), PL-15,82; DD-4,23; DK-0,50; DL-5,65',
            'PER TARIK SS, PL1-25,89; PL2-10,69; DD-8,21; DL1-19,04; DL2-11,87',
            'PER TARIK UK. 0,5 MM',
            'PER TARIK, PL-95,69; DD-15,06; DK-1,77; DL-19,70',
            'PER TEKAN FILLING JV02 UK. P: 65MM, OD: 12MM, ID: 8,5MM, TEBAL: 1,6MM, ULIR: 19,8',
            'PER TEKAN HORIZONTAL (PER TEKAN STEEL 3mm x 12,5mm x 45mm 7 lilitan) MESIN STICK',
            'PER TEKAN HORIZONTAL JELLY GUM ALUNG',
            'PER TEKAN HORIZONTAL KJT, PL-50,82; DD-20,67; DK-4,77; DL-30,63; L-7',
            'PER TEKAN HORIZONTAL MASEMA',
            'PER TEKAN IMPORT "STEEL", PL-90; DD-15; DK-2,5; DL-23; L-12',
            'PER TEKAN MESIN C5, PL-58,22; DD-40,27; DK-5,12; DL-51,61; L-5',
            'PER TEKAN MESIN STICK, PL-35,36; DD-11,71; DK-3; DL-18,5; L-5',
            'PER TEKAN MESIN STICK, PL-45; DD-12,5; DK-2,5; DL-18,5; L-7',
            'PER TEKAN PRESSAN, MESIN JG PL-51,02; DD-14,95; DK-3,02; DL-21,10; L-7',
            'PER TEKAN SS 1,5MM X 13MM X 16MM X 40MM',
            'PER TEKAN SS 1,5MM X 14,5 X 17,5 X 50MM (ULIR 8) C10',
            'PER TEKAN SS FILLING MESIN UHT 3MM X 14MM X 20 MM X 50 MM (ULIR 8)',
            'PER TEKAN STEEL 1.5x13x16x40mm',
            'PER TEKAN STEEL, PL-60; DD-18; DK-4; DL-26; L-6',
            'PER TEKAN VERTICAL, P: 2,7 CM, DL: 2 CM',
            'PER TEKAN, PL-57,11; DD-15,73; DK-2; DL-20,02; L-10',
            'PER TEKAN, PL-61,32; DD-22,02; DK-3,95; DL-29,97; L-6',
            'PER TEKAN, PL-72,24; DD-25,27; DK-6,27; DL-37,80; L-5',
            'PER TEKAN, PL-90,04; DD-16,02; DK-2,61; DL-29,70; L-14',
            'PHOTO SENSOR BR100 - DDT AUTONICS',
            'PILLOW BLOCK BEARING 204',
            'PILLOW BLOCK BEARING 204 UCFB',
            'PILLOW BLOCK UCP 204',
            'PIPA 1 1/2 INCH SS - 2 METER',
            'PIPA SANITARY 38 MM / 1,5 INCH',
            'PISAU CARTON SEALER 65 X 25 X 1,2',
            'PISAU PAVO 120CR UK. 250',
            'PISAU PUNCH FULL AUTO 82 X 23T X 50 MM',
            'PISAU TUNG-TUNG',
            'PISAU ZIGZAG UK. 200',
            'PISTON SILINDER PUMP',
            'PITA EXPIRE DATE LB5 WARNA PUTIH',
            'PNEUMATIC COMPONENTS E-MC PRESSURE 0,15-0,8 MPA ISO 9001 EW-3000',
            'PNEUMATIC COMPONENTS E-MC PRESSURE 0,15-0,8 MPA ISO 9001 RV5241-15E2',
            'POWER SUPPLY 220V AC 12V DC',
            'POWER SUPPLY 220V AC 24V DC',
            'POWER SUPPLY 24V 10A',
            'POWER SUPPLY FIX TYPE S82Y - FSC150DIN',
            'POWER SUPPLY OUTPUT 24V 30A',
            'POWER SUPPLY SPA-050-24',
            'POWER SUPPLY SPA-100-24',
            'POWER WINDOW SWITCH 0501W',
            'PRESSAN HORIZONTAL',
            'PRESSAN VERTICAL',
            'PROXIMITY PR12-4DN SENSOR AUTONICS',
            'PROXIMITY SENSOR AUTONICS PR12-2DN',
            'PROXIMITY SENSOR AUTONICS PRD12-4DN',
            'PROXIMITY SENSOR AUTONICS PRL12-2DN',
            'PROXIMITY SENSOR AUTONICS PRL12-4DN',
            'PROXIMITY SENSOR AUTONICS PS12-4DN',
            'PUSH BUTTON CR 254 A0 HANYOUNG',
            'REDUCER 1 1/2 INCH X 1/2 INCH GALVANIS',
            'REDUCER 1 1/4 INCH X 1 INCH GIV',
            'REDUCER 1 1/4 INCH X 1/2 INCH GALVANIS',
            'REDUCER 1 1/4 INCH X 1/2 INCH SS',
            'REDUCER 1 X 1 1/2 INCH PVC',
            'REDUCER 1 X 3/4 INCH PVC',
            'REDUCER 1 X 3/4 INCH SS',
            'REDUCER 2 INCH X 1 1/2 INCH SS 201',
            'REDUCER 2 INCH X 1 INCH SS',
            'REDUCER 2 INCH X 1/2 INCH PVC',
            'REDUCER 2 X 1 1/2 INCH GALVANIS',
            'REDUCER 2 X 1 1/2 INCH SS',
            'REDUCER 3 INCH X 1 1/2 INCH PVC',
            'REDUCER 3 INCH X 2 1/2 INCH PVC',
            'REDUCER 3 X 2 INCH PVC',
            'REDUCER 3/4 INCH X 1/2 INCH PVC',
            'REDUCER 3/4 INCH X 1/2 INCH SS',
            'REDUCER 4 INCH X 2 INCH PVC',
            'REDUCER 4 INCH X 3 INCH PVC',
            'REDUCER 4 X 3 INCH PVC',
            'REDUCER 8 INCH X 5 INCH PVC',
            'REDUCER UK 1 1/4 INCH - 1 INCH',
            'REGULATOR R3000 MERK CKD',
            'RELAY BENTELY SSR ST5-5DD INPUT 24VDC',
            'RELAY OMRON MK2P-N 220V AC 8 KAKI',
            'RELAY OMRON MK2P-N 24V DC 8 KAKI',
            'RELAY OMRON MKS2P 250V AC',
            'RELAY FOTEX 20 DA',
            'REPAIR KIT PT CKD',
            'RESISTOR 2W 1OHM',
            'RESITOR 2W 1 OHM',
            'RING BAN',
            'ROD END M8 X 1,25 - L',
            'RODA 8 INCH',
            'RODA TROLI 5 INCH',
            'RODA TROLI 6 INCH FLEXIBLE',
            'RODA TROLI 6 INCH MATI',
            'RODA TROLI KARET 4 INCH',
            'RUBBER KOPLING F2',
            'RUBBER KOPLING F3',
            'RUMAH BEARING STICK',
            'RUMAH KARAKTER ANGKA SALJU - TJM',
            'RUMAH TOZEN POMPA INLET',
            'SARUNG TANGAN KAIN BINTIK',
            'SEAL EXPIRE SALJU',
            'SEAL FERULLE 1 INCH',
            'SEAL FERULLE 1/2 INCH',
            'SEAL FERULLE 2 INCH',
            'SEAL FERULLE 3/4 INCH (JV02)',
            'SEAL FERULLE UK 1,5 INCH',
            'SEAL FERULLE UK 2 INCH',
            'SEAL FILLING VALVE',
            'SEAL HAND PALLET',
            'SEAL KIT NORGREN QA/8032/00',
            'SEAL PRESSAN VERTICAL UKURAN 180 (MESIN JG & SALJU)',
            'SEAL PRESSAN VERTIKAL UK. 150MM (JELLY GUM)',
            'SEAL RODA',
            'SEAL TEFLON PISTON UK 40MM',
            'SEAL UNION JOINT',
            'SEGITIGA PENGAMAN',
            'SEKOP BATUBARA',
            'SELANG ANGIN PU 5 X 10MM',
            'SELANG ANGIN PU 8,5 X 14MM',
            'SELANG ANGIN PU UK 14MM',
            'SELANG ANGIN UK. 16 X 12MM',
            'SELANG BENANG 1 1/4 INCH',
            'SELANG BENANG 1 INCH',
            'SELANG BENANG 1/2 INCH',
            'SELANG BENANG 1/4 INCH',
            'SELANG BENANG 3/4 INCH',
            'SELANG BENANG 3/8',
            'SELANG BENANG FOODGRADE 5/8 INCH',
            'SELANG BENANG NYLON 1 INCH',
            'SELANG FLEKSIBLE 30 CM SS',
            'SELANG FOOD GRADE 1 1/2 INCH KAWAT',
            'SELANG FOOD GRADE 1 1/4 INCH',
            'SELANG FOOD GRADE 1 INCH KAWAT',
            'SELANG FOOD GRADE 3/4 INCH (SERAT BENANG)',
            'SELANG FOOD GRADE 3/4 INCH KAWAT',
            'SELANG FOOD GRADE UK. 1 INCH BENANG',
            'SELANG KAWAT 1/2 INCH',
            'SELANG KAWAT 25 X 3',
            'SELANG KAWAT 3/8 INCH',
            'SELANG KAWAT 5/8 INCH',
            'SELANG KAWAT PVC 1 INCH',
            'SELANG KAWAT PVC 2 INCH',
            'SELANG KUNIMG AIR HOSE 8.5 X 12',
            'SELANG NYLON UK 16MM X 13MM',
            'SELANG RADIATOR',
            'SELANG SILICONE 1/2 INCH',
            'SELANG SILICONE 5/8 INCH',
            'SELANG SILICONE OD: 6 MM X ID: 4 MM',
            'SELANG SILICONE UK. 12 MM X 16 MM',
            'SELANG SILICONE UK. 8 MM X 12 MM',
            'SELANG STEMPET',
            'SELECTOR SWITCH HB2511X/21 5A, MERK FORT',
            'SELENDANG F 20',
            'SENSOR GL-518NO (MESIN SEAL CARTON)',
            'SENSOR MESIN DATE CODING',
            'SENSOR NBSKK',
            'SENTER KEPALA LED 10 WATT',
            'SERVO RS 20-536',
            'SHAFT PISTON FILLING 5X1,8',
            'SHOCK BEKER BELAKANG',
            'SHOCK BEKER DEPAN',
            'SHOCK BEKER DEPAN FUSO',
            'SILENCER 1/4 INCH',
            'SILENCER 10A 3/8 INCH',
            'SILENCER 4/8 INCH',
            'SILENCER 5/8 INCH',
            'SILENCER 1/8 INCH',
            'SILICONE RUBBER 5 MM X 2 MM (ALU) X 18,5 MM X 100 MM, RED',
            'SILICONE RUBBER ROBOKIDZ',
            'SILICONE RUBBER UK 3MM X 500MM X 1000MM',
            'SILICONE RUBBER UK 4MM X 50MM X 100MM',
            'SILICONE RUBBER UK 6MM X 50MM X 100CM',
            'SKUN SOCK 4 MM',
            'SKUN SOCK 6 MM',
            'SKUN SOCK 8 MM',
            'SNAP RING',
            'SNAPRING R30',
            'SNAPRING R-30',
            'SOCK 2 1/2 INCH PVC',
            'SOCK 3/4 INCH PVC',
            'SOCK 4 INCH PVC',
            'SOCK 5 INCH PVC',
            'SOCK DRAT 1 INCH SS 304',
            'SOCK DRAT DALAM 1 1/2 INCH GALVANIS',
            'SOCK DRAT DALAM 1 1/2 SS',
            'SOCK DRAT DALAM 1 1/4 INCH GALVANIS',
            'SOCK DRAT DALAM 1 1/4 INCH SS',
            'SOCK DRAT DALAM 1 INCH GALVANIS',
            'SOCK DRAT DALAM 1 INCH PVC',
            'SOCK DRAT DALAM 1/2 INCH GALVANIS',
            'SOCK DRAT DALAM 1/2 INCH PVC',
            'SOCK DRAT DALAM 1/2 INCH SS',
            'SOCK DRAT DALAM 2 INCH GALVANIS',
            'SOCK DRAT DALAM 2 INCH PVC',
            'SOCK DRAT DALAM 2 INCH SS',
            'SOCK DRAT DALAM 2.5 INCH GALVANIS',
            'SOCK DRAT DALAM 3 INCH GALVANIS',
            'SOCK DRAT DALAM 3 INCH PVC',
            'SOCK DRAT DALAM 3/4 INCH GALVANIS',
            'SOCK DRAT DALAM 3/4 INCH PVC',
            'SOCK DRAT DALAM 3/4 INCH SS',
            'SOCK DRAT DALAM 4 INCH PVC',
            'SOCK DRAT LUAR 1 INCH GALVANIS',
            'SOCK DRAT LUAR 1 INCH PVC',
            'SOCK DRAT LUAR 1 INCH X 3/4 INCH PVC',
            'SOCK DRAT LUAR 1/2 INCH GALVANIS',
            'SOCK DRAT LUAR 2 1/2 INCH PVC',
            'SOCK DRAT LUAR 2 INCH PVC',
            'SOCK DRAT LUAR 2.5 INCH GALVANIS',
            'SOCK DRAT LUAR 3 INCH PVC',
            'SOCK DRAT LUAR 3/4 INCH PVC',
            'SOCK DRAT LUAR 4 INCH PVC',
            'SOCKET RELAY LY2N 8 PIN - PTF08A',
            'SOLAR GENSET',
            'SOLID STATE RELAY 240V AC 10 AMP',
            'SOLID STATE RELAY KSD240AC8 MERK COSMO',
            'SPIDOL PUTIH PERMANENT',
            'SPROCKET MODULAR CONVEYOR T12 SHAFT HOLLO 40 MM',
            'SPROKET 40 X 15',
            'SPROKET 40 X 20',
            'SPUR GEAR MESIN JG',
            'SSR AUTONICS SRH1-1215-N MERK AUTONICS 24-240V AC',
            'STABILIZER MATSUNAGA 1000 VA',
            'STAIN CLEAN NIKKO STEEL',
            'STEKER BROCO',
            'STOP KONTAK 1 TOMBOL',
            'STOP KONTAK 2 TOMBOL',
            'STOP KONTAK ISI 4 BROCO',
            'SURFACE MOUNTING WALL SOCKET',
            'SWITCH ON OFF KCD4',
            'TABUNG RADIATOR - FUSO PS200 TURBO',
            'TAP 68 90 10',
            'TEE 1 1/4 INCH GALVANIS',
            'TEE 1 1/4 INCH PVC',
            'TEE 1 INCH GALVANIS',
            'TEE 1 INCH PVC',
            'TEE 1 INCH SS',
            'TEE 1/2 INCH GALVANIS',
            'TEE 1/2 INCH PVC',
            'TEE DRAT DALAM 1 1/4 INCH GALVANIS',
            'TEE DRAT DALAM 1 INCH SS',
            'TEE DRAT DALAM 2 INCH GALVANIS',
            'TEE DRAT DALAM 3/4 INCH SS',
            'TEFLON MERAH PJG 11,5 X 4,5 CM',
            'TEFLON MERAH UK. 1000M X 1000M X 6 MM',
            'TEFLON SEAL SILICONE 59,5 X 31,5 X 17 MM',
            'TEMPERATURE CONTROL AX2-1A',
            'TEMPERATURE CONTROL FOTEX MT72 - V',
            'TEMPERATURE CONTROL HANYOUNG FT-C400',
            'TEMPERATURE CONTROL HANYOUNG NUX AF1 PKN1NR07 50 HZ',
            'TEMPERATURE CONTROLLER (CODING MS 200)',
            'Temperature Controller DELTA DTK4848V01',
            'TERMINAL BLOCK ISI 24',
            'TERMINAL KERAMIK 10 A',
            'TERMINAL ISI 2',
            'TERMINAL ISI 6',
            'THERMAL OVERLOAD SCHNEIDER LRD32 (29-32A)',
            'THERMAL OVERLOAD SCHNEIDER LRD35 (30-38A)',
            'THERMOMETER DIGITAL KRISCHEFT',
            'THREAD LOCKER MERK GRIP ON DIN 838',
            'TIE ROD',
            'TIMAH KAWAT',
            'TOMBOL ON OFF KOTAK',
            'TOZEN VALVE ATAS',
            'TOZEN VALVE BAWAH',
            'TRAY',
            'TULISAN AIR DINGIN/ AIR PANAS',
            'TUSEN KLEP 2 INCH KUNINGAN',
            'TUSEN KLEP 3 INCH KUNINGAN',
            'TUTUP LAMPU / RUBBER DIAPHARAM',
            'VACUM PUMP BM 10-A',
            'VAN BELT 26 V4',
            'VAN BELT A 21',
            'VAN BELT A 22',
            'VAN BELT A 23',
            'VAN BELT A 33',
            'VAN BELT A 34',
            'VAN BELT A 36',
            'VAN BELT A 49',
            'VAN BELT A 50',
            'VAN BELT A 52',
            'VAN BELT A 54',
            'VAN BELT B 51',
            'VAN BELT B 72',
            'VAN BELT B 73',
            'VAN BELT B 77',
            'VAN BELT B 85',
            'VAN BELT B L1',
            'VAN BELT GIGI 5 KM (N)',
            'VAN BELT K 25',
            'VELK BAN',
            'WATER MUR 1 1/2 INCH PVC',
            'WATER MUR 1 1/2 INCH SS',
            'WATER MUR 1 1/2 INCH SS 201',
            'WATER MUR 1 1/4 INCH GALVANIS',
            'WATER MUR 1 INCH GIV',
            'WATER MUR 1 INCH PVC',
            'WATER MUR 1 INCH SS',
            'WATER MUR 1/2 INCH PVC',
            'WATER MUR 1/2 INCH SS',
            'WATER MUR 2 INCH GALVANIS',
            'WATER MUR 2 INCH PVC',
            'WATER MUR 2 INCH SS 201',
            'WATER MUR 2.5 INCH GALVANIS',
            'WATER MUR 3 INCH PVC',
            'WATER MUR 4 INCH PVC',
            'WATER PUMP F3',
            'WATER SPARATOR - FUSO PS200 TURBO',
            'WEBBING BELT 2MM',
            'WIFER KACA PS 220 (FUSO)',
            'WIPER KACA MOBIL CANTER PS 125',
            'WIRE MASH 40',
            'Y STRAINER 2 INCH KUNINGAN',
            'KLEM SELANG 1 1/4 INCH',
            'PUSH BUTTON CRF-F25M1R 4 KAKI 5A - HIJAU',
            'PUSH BUTTON CRF-F25M1R 4 KAKI 5A - MERAH',
            'LAMPU INLITE 18 WATT LED + BOX (INTE 002)',
            'PUSH BUTTON PB25 2 KAKI 6A - MERAH',
            'PUSH BUTTON PB25 2 KAKI 6A - HIJAU',
            'TEFLON MERAH UK. 1000M X 1000M X 8 MM',
            'FITTING APC 8',
            'TEFLON BELT 810 X 15 MM (MC.SEALER FRM-980)',
            'BUSHING MEKANIK PISAU ES SALJU',
            'MECHANICAL SEAL POMPA MS-160',
            'REDUCER 1 1/2 INCH X 1 1/4 INCH SS',
            'KARAKTER 3 X 3,5 X 6,8 R ANGKA 0 (HRZ)',
            'KARAKTER 3 X 3,5 X 6,8 R ANGKA 1 (HRZ)',
            'KARAKTER 3 X 3,5 X 6,8 R ANGKA 2 (HRZ)',
            'KARAKTER 3 X 3,5 X 6,8 R ANGKA 3 (HRZ)',
            'KARAKTER 3 X 3,5 X 6,8 R ANGKA 4 (HRZ)',
            'KARAKTER 3 X 3,5 X 6,8 R ANGKA 5 (HRZ)',
            'KARAKTER 3 X 3,5 X 6,8 R ANGKA 6 (HRZ)',
            'KARAKTER 3 X 3,5 X 6,8 R ANGKA 7 (HRZ)',
            'KARAKTER 3 X 3,5 X 6,8 R ANGKA 8 (HRZ)',
            'KARAKTER 3 X 3,5 X 6,8 R ANGKA 9 (HRZ)',
            'BATERAI ABC R14C',
            'HALBASIT BELT 1650 X 250',
            'VALVE ENGINE 399-181',
            'SENSOR FOTEX QL-05N 30VDC',
            'RUBBER SILICONE RED (PLAT ALUMUNIUM) 71,5 MM x 25 MM x 8 MM',
            'HEATER CATRIDGE ILF 250W 220V, 121 MM X 7,5 MM, KABEL 25 CM',
            'KABEL NYM 2 X 1,5 MM',
            'SPEED ADJUSTING FRB KAKI 8',
            'MAIN CONTROL PCB FRB + PCB BOARD FRB KAKI 11',
            'SELANG KAWAT 1 1/2 INCH',
            'STECKER BROCO',
            'KARAKTER 2 X 4 X 14,5 HURUF E',
            'KARAKTER 2 X 4 X 14,5 HURUF F',
            'KARAKTER 2 X 4 X 14,5 HURUF G',
            'KARAKTER 2 X 4 X 14,5 HURUF P',
            'KARAKTER 2 X 4 X 14,5 HURUF X',
            'CARBON BRUSH CB 325',
            'KARAKTER 3 X 3,0 X 6,8 HURUF M (HRZ)',
            'KARAKTER 3 X 3,0 X 6,8 HURUF A (HRZ)',
            'KARAKTER 3 X 3,0 X 6,8 HURUF S (HRZ)',
            'HEATER CATRIDGE 175W 110V,  Ø8 MM X 150 MM, KABEL 25 CM',
            'SAMBUNGAN MATA RANTAI N0. 60 1WBA 1PIN SS',
            'PISAU GIGI P: 270',
            'OIL SEAL TC 25-45-8',
            'BEARING 30205',
            'RUBBER SILICONE RED (PLAT ALUMUNIUM) 30 CM x 30 CM x 8 MM',
            'Filter Udara ME416307',
            'HEATER CATRIDGE 1500W 220V, Ø 15 MM X 735 MM, KABEL FLEKSIBLE 25 CM',
            'Van Belt A 41',
            'PER TEKAN "STAINLESS STEEL 1 MM x 15 MM x 17 MM x 60 MM" CK01',
            'Bearing Pillow Block UCP 205 - 25 MM',
            'Selang Silicone 3/8 Inch',
            'Elbow 3/4 Inch PVC AW',
            'Selang Benang 1 1/2 Inch',
            'Oli Gear Box SAE 90',
            'MAGNETIC SWITCH EWIG MODEL MS-N10 COIL 380 (5,2-8 A)',
            'KRAN COMPRESSOR ANGIN 1/4 INCH CHROME',
            'SPROCKET MODULAR CONVEYOR T12 SHAFT HOLLO 40 MM',
            'BATERAI LITHIUM CR2032',
            'Belt Conveyor Uk. 370 x 2.950 MM Endless, PVC Hitam 3 MM',
            'Belt Conveyor Uk. 200 x 2.000 MM Endless, PVC Putih 2 MM',
            'Belt Conveyor Uk. 200 x 1.700 MM Endless, PVC Putih 2 MM',
            'Cat NO DROP',
            'BALING-BALING AGITATOR',
            'MCCB 3 PHASE 40 A',
            'UNIVERSAL CODING SOLVENT',
            'DOP 57 x 7 x 2',
            'HEATER CATRIDGE 250W 220V, 121 MM X 7,5 MM, KABEL 25 CM',
            'Make Up Hitachi',
            'ORING WHITE SILICONE ID: 4 MM, OD: 8 MM, CS: 2 MM (FH)',
            'MAKE UP MC-2BK130',
            'TINTA IC-2BK130',
            'RELAY FOTEX SSR-20 DA',
            'SELANG NYLON 6 X 4 MM',
            'MCB 3 PHASE 40A',
            'RELAY FOTEX SSR-10 DA',
            'ORING WHITE SILICONE ID: 20 MM, CS: 2,7 MM',
            'Pisau Zigzag Uk. 200 ( KM 1200 RB )',
            'BALL VALVE 2 1/2 INCH PVC',
            'Lampu Celup Aquarium 20 Cm ( Putih )',
            'CLEANER SOLVENT',
            'CHECK VALVE 3 INCH PVC',
            'HEATER CATRIDGE 80W 220V, 8 MM X 36 MM, KABEL FLEXIBLE 12 CM',
            'ORING WHITE SILICONE 1,9 X 8,8 X 12,6 MM (NF)',
            'BEARING 6306 2RS SKF',
            'Per Tarik Steel "2,2 mm x 18 mm x 22,5 mm x 134 mm (Ulir 61)" Carton Sealer',
            'Per Tekan Steel "3,10 mm x 11,35 mm x 18,15 mm x 42,60 mm (Ulir 7)" Stick',
            'Kapasitor 10 uF',
            'PROXIMITY SENSOR PRL12-2DN AUTONICS (7 CM)',
            'ORING WHITE SILICONE ID: 4 MM, OD: 8 MM, CS: 2 MM (FH)',
            'KAPASITOR 6 uF 450V AC',
            'Catridge Solvent 53S+ Goldjet',
            'PER TEKAN SS "1,5 MM X 8,5 MM X 11,5 MM X  65 MM" 19 ULIR - FJV',
            'PER TEKAN CHROME 1,5 MM X 14,5 X 17,5 X 95 MM (ULIR 15) - JV01',
            'Bearing 6010 2RS / C3 SKF',
            'Oil Seal TC 40-60-8',
            'ORING RED SILICONE OD: 31,15 MM, ID: 25,7 MM, CS: 3,5 MM',
            'ORING RED SILICONE OD: 48,31 MM, ID: 44,4 MM, CS: 3,5 MM',
            'ORING WHITE SILICONE ID: 6,35 MM, OD: 9,92 MM, CS: 1,76 MM',
            'ORING WHITE SILICONE ID: 51,8 MM, OD: 58,8 MM, CS: 3,7 MM (FP)',
            'Fitting ( + )  8 MM',
            'PER TEKAN SS304 Ø2,5 MM, OD: 27 MM, ID: 22 MM, P: 31 MM, LILITAN: 4',
            'ORING RED SILICONE ID: 51,8 MM, OD: 58,8 MM, CS: 3,7 MM (FP)',
            'ORING GREEN SILICONE ID: 21 MM, OD: 26 MM, CS: 2,7 MM',
            'ORING GREEN SILICONE ID: 14 MM, OD: 19 MM, CS: 2,7 MM',
            'MATA GERINDA POLES AMPLAS GRIT A 80 4 INCH / FLAP DISK',
            'KAWAT TALI LUNAK 0,8 MM SS',
        ];

        
        foreach ($spareparts as $partName) {
            Product::create([
                'name' => $partName,
                'sku' => null, 
                'stock' => rand(10, 100), 
                'minimum_stock' => rand(5, 10), 
                'lifetime_penggunaan' => rand(90, 730), 
                'unit' => 'pcs', 
                'price' => rand(25000, 2000000),
                'image' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}